//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dEvent_exception_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public s32 mEventInfoIdx {get => this._mEventInfoIdx(); set => this._mEventInfoIdx(value);}//;
        
        public s32 field_0x4 {get => this._field_0x4(); set => this._field_0x4(value);}//;
        
        public s32 mState {get => this._mState(); set => this._mState(value);}//;
        
        public dEvent_exception_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private s32 _mEventInfoIdx() {
            return Memory.RAM.ReadS32(this.pointer + 0x0);
        }
        
        private void _mEventInfoIdx(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x0, value);
        }
        
        private s32 _field_0x4() {
            return Memory.RAM.ReadS32(this.pointer + 0x4);
        }
        
        private void _field_0x4(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x4, value);
        }
        
        private s32 _mState() {
            return Memory.RAM.ReadS32(this.pointer + 0x8);
        }
        
        private void _mState(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x8, value);
        }
    }
}
