//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class scene_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        //public process_node_class mBase {get => this._mBase(); set => this._mBase(value);}//;
        
        public scene_method_class mpMtd {get => this._mpMtd(); set => this._mpMtd(value);}//;
        
        public scene_tag_class mScnTg {get => this._mScnTg(); set => this._mScnTg(value);}//;
        
        public scene_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
/*        
        private process_node_class _mBase() {
            return new process_node_class(this.pointer + 0x000);
        }
        
        private void _mBase(process_node_class value) {
        }
        */
        private scene_method_class _mpMtd() {
            return new scene_method_class(this.pointer + 0x1AC);
        }
        
        private void _mpMtd(scene_method_class value) {
        }
        
        private scene_tag_class _mScnTg() {
            return new scene_tag_class(this.pointer + 0x1B0);
        }
        
        private void _mScnTg(scene_tag_class value) {
        }
    }
}
