//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dNpc_PathRun_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        //public dPath mPath {get => this._mPath(); set => this._mPath(value);}//;
        
        public u8 field_0x04 {get => this._field_0x04(); set => this._field_0x04(value);}//;
        
        public u8 mCurrPointIndex {get => this._mCurrPointIndex(); set => this._mCurrPointIndex(value);}//;
        
        public u8 mbGoingForwards {get => this._mbGoingForwards(); set => this._mbGoingForwards(value);}//;
        
        public u8 field_0x07 {get => this._field_0x07(); set => this._field_0x07(value);}//;
        
        public dNpc_PathRun_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
       /* private dPath _mPath() {
            return new dPath(this.pointer + 0x00);
        }
        
        private void _mPath(dPath value) {
        }*/
        
        private u8 _field_0x04() {
            return Memory.RAM.ReadU8(this.pointer + 0x04);
        }
        
        private void _field_0x04(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x04, value);
        }
        
        private u8 _mCurrPointIndex() {
            return Memory.RAM.ReadU8(this.pointer + 0x05);
        }
        
        private void _mCurrPointIndex(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x05, value);
        }
        
        private u8 _mbGoingForwards() {
            return Memory.RAM.ReadU8(this.pointer + 0x06);
        }
        
        private void _mbGoingForwards(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x06, value);
        }
        
        private u8 _field_0x07() {
            return Memory.RAM.ReadU8(this.pointer + 0x07);
        }
        
        private void _field_0x07(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x07, value);
        }
    }
}
