//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dNpc_HeadAnm_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public s16 field_0x00 {get => this._field_0x00(); set => this._field_0x00(value);}//;
        
        public s16 field_0x02 {get => this._field_0x02(); set => this._field_0x02(value);}//;
        
        public u32 field_0x04 {get => this._field_0x04(); set => this._field_0x04(value);}//;
        
        //public swing_func mFunc {get => this._mFunc(); set => this._mFunc(value);}//;
        
        public f32 field_0x14 {get => this._field_0x14(); set => this._field_0x14(value);}//;
        
        public f32 field_0x18 {get => this._field_0x18(); set => this._field_0x18(value);}//;
        
        public s16 field_0x1C {get => this._field_0x1C(); set => this._field_0x1C(value);}//;
        
        public s16 field_0x1E {get => this._field_0x1E(); set => this._field_0x1E(value);}//;
        
        public s16 field_0x20 {get => this._field_0x20(); set => this._field_0x20(value);}//;
        
        public dNpc_HeadAnm_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private s16 _field_0x00() {
            return Memory.RAM.ReadS16(this.pointer + 0x00);
        }
        
        private void _field_0x00(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x00, value);
        }
        
        private s16 _field_0x02() {
            return Memory.RAM.ReadS16(this.pointer + 0x02);
        }
        
        private void _field_0x02(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x02, value);
        }
        
        private u32 _field_0x04() {
            return Memory.RAM.ReadU32(this.pointer + 0x04);
        }
        
        private void _field_0x04(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x04, value);
        }
        
/*        private swing_func _mFunc() {
            return new swing_func(this.pointer + 0x08);
        }
        
        private void _mFunc(swing_func value) {
        }*/
        
        private f32 _field_0x14() {
            return Memory.RAM.ReadF32(this.pointer + 0x14);
        }
        
        private void _field_0x14(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x14, value);
        }
        
        private f32 _field_0x18() {
            return Memory.RAM.ReadF32(this.pointer + 0x18);
        }
        
        private void _field_0x18(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x18, value);
        }
        
        private s16 _field_0x1C() {
            return Memory.RAM.ReadS16(this.pointer + 0x1C);
        }
        
        private void _field_0x1C(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x1C, value);
        }
        
        private s16 _field_0x1E() {
            return Memory.RAM.ReadS16(this.pointer + 0x1E);
        }
        
        private void _field_0x1E(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x1E, value);
        }
        
        private s16 _field_0x20() {
            return Memory.RAM.ReadS16(this.pointer + 0x20);
        }
        
        private void _field_0x20(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x20, value);
        }
    }
}
