//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WW.API {
    
    
    public class WrapperVec3i {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public s32 x {get => this._x(); set => this._x(value);}//;
        
        public s32 y {get => this._y(); set => this._y(value);}//;
        
        public s32 z {get => this._z(); set => this._z(value);}//;
        
        public WrapperVec3i(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0C;
        }
        
        private s32 _x() {
            return Memory.RAM.ReadS32(this.pointer + 0x00);
        }
        
        private void _x(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x00, value);
        }
        
        private s32 _y() {
            return Memory.RAM.ReadS32(this.pointer + 0x04);
        }
        
        private void _y(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x04, value);
        }
        
        private s32 _z() {
            return Memory.RAM.ReadS32(this.pointer + 0x08);
        }
        
        private void _z(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x08, value);
        }
    }
}
