//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class msg_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 mMsgType {get => this._mMsgType(); set => this._mMsgType(value);}//;
        
        //public create_tag_class mDwTg {get => this._mDwTg(); set => this._mDwTg(value);}//;
        
        public msg_method_class mSubMtd {get => this._mSubMtd(); set => this._mSubMtd(value);}//;
        
        public fopAc_ac_c mpActor {get => this._mpActor(); set => this._mpActor(value);}//;
        
        public cXyz mPos {get => this._mPos(); set => this._mPos(value);}//;
        
        public u32 mMsgID {get => this._mMsgID(); set => this._mMsgID(value);}//;
        
        public u32 field_0xf0 {get => this._field_0xf0(); set => this._field_0xf0(value);}//;
        
        public u32 field_0xf4 {get => this._field_0xf4(); set => this._field_0xf4(value);}//;
        
        public u16 mStatus {get => this._mStatus(); set => this._mStatus(value);}//;
        
        public u8 mSelectNum {get => this._mSelectNum(); set => this._mSelectNum(value);}//;
        
        public msg_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0xFC;
        }
        
        private u32 _mMsgType() {
            return Memory.RAM.ReadU32(this.pointer + 0xC0);
        }
        
        private void _mMsgType(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0xC0, value);
        }
        
/*        private create_tag_class _mDwTg() {
            return new create_tag_class(this.pointer + 0xC4);
        }
        
        private void _mDwTg(create_tag_class value) {
        }*/
        
        private msg_method_class _mSubMtd() {
            return new msg_method_class(this.pointer + 0xD8);
        }
        
        private void _mSubMtd(msg_method_class value) {
        }
        
        private fopAc_ac_c _mpActor() {
            return new fopAc_ac_c(this.pointer + 0xDC);
        }
        
        private void _mpActor(fopAc_ac_c value) {
        }
        
        private cXyz _mPos() {
            return new cXyz(this.pointer + 0xE0);
        }
        
        private void _mPos(cXyz value) {
        }
        
        private u32 _mMsgID() {
            return Memory.RAM.ReadU32(this.pointer + 0xEC);
        }
        
        private void _mMsgID(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0xEC, value);
        }
        
        private u32 _field_0xf0() {
            return Memory.RAM.ReadU32(this.pointer + 0xF0);
        }
        
        private void _field_0xf0(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0xF0, value);
        }
        
        private u32 _field_0xf4() {
            return Memory.RAM.ReadU32(this.pointer + 0xF4);
        }
        
        private void _field_0xf4(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0xF4, value);
        }
        
        private u16 _mStatus() {
            return Memory.RAM.ReadU16(this.pointer + 0xF8);
        }
        
        private void _mStatus(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0xF8, value);
        }
        
        // Theindexofthechoicetheplayerselected.
        private u8 _mSelectNum() {
            return Memory.RAM.ReadU8(this.pointer + 0xFA);
        }
        
        private void _mSelectNum(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0xFA, value);
        }
    }
}
