//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class fopMsgM_pane_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        //public J2DPane pane {get => this._pane(); set => this._pane(value);}//;
        
        public cXy mPosTopLeftOrig {get => this._mPosTopLeftOrig(); set => this._mPosTopLeftOrig(value);}//;
        
        public cXy mPosTopLeft {get => this._mPosTopLeft(); set => this._mPosTopLeft(value);}//;
        
        public cXy mPosCenterOrig {get => this._mPosCenterOrig(); set => this._mPosCenterOrig(value);}//;
        
        public cXy mPosCenter {get => this._mPosCenter(); set => this._mPosCenter(value);}//;
        
        public cXy mSizeOrig {get => this._mSizeOrig(); set => this._mSizeOrig(value);}//;
        
        public cXy mSize {get => this._mSize(); set => this._mSize(value);}//;
        
        public u8 mInitAlpha {get => this._mInitAlpha(); set => this._mInitAlpha(value);}//;
        
        public u8 mNowAlpha {get => this._mNowAlpha(); set => this._mNowAlpha(value);}//;
        
        public s16 mUserArea {get => this._mUserArea(); set => this._mUserArea(value);}//;
        
        public fopMsgM_pane_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
/*        private J2DPane _pane() {
            return new J2DPane(this.pointer + 0x00);
        }
        
        private void _pane(J2DPane value) {
        }*/
        
        private cXy _mPosTopLeftOrig() {
            return new cXy(this.pointer + 0x04);
        }
        
        private void _mPosTopLeftOrig(cXy value) {
        }
        
        private cXy _mPosTopLeft() {
            return new cXy(this.pointer + 0x0C);
        }
        
        private void _mPosTopLeft(cXy value) {
        }
        
        private cXy _mPosCenterOrig() {
            return new cXy(this.pointer + 0x14);
        }
        
        private void _mPosCenterOrig(cXy value) {
        }
        
        private cXy _mPosCenter() {
            return new cXy(this.pointer + 0x1C);
        }
        
        private void _mPosCenter(cXy value) {
        }
        
        private cXy _mSizeOrig() {
            return new cXy(this.pointer + 0x24);
        }
        
        private void _mSizeOrig(cXy value) {
        }
        
        private cXy _mSize() {
            return new cXy(this.pointer + 0x2C);
        }
        
        private void _mSize(cXy value) {
        }
        
        private u8 _mInitAlpha() {
            return Memory.RAM.ReadU8(this.pointer + 0x34);
        }
        
        private void _mInitAlpha(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x34, value);
        }
        
        private u8 _mNowAlpha() {
            return Memory.RAM.ReadU8(this.pointer + 0x35);
        }
        
        private void _mNowAlpha(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x35, value);
        }
        
        private s16 _mUserArea() {
            return Memory.RAM.ReadS16(this.pointer + 0x36);
        }
        
        private void _mUserArea(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x36, value);
        }
    }
}
