//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class fopMsg_prm_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public fopAc_ac_c mpActor {get => this._mpActor(); set => this._mpActor(value);}//;
        
        public cXyz mPos {get => this._mPos(); set => this._mPos(value);}//;
        
        public u32 mMsgID {get => this._mMsgID(); set => this._mMsgID(value);}//;
        
        public u32 field_0x14 {get => this._field_0x14(); set => this._field_0x14(value);}//;
        
        public u32 field_0x18 {get => this._field_0x18(); set => this._field_0x18(value);}//;
        
        public fopMsg_prm_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x1C;
        }
        
        private fopAc_ac_c _mpActor() {
            return new fopAc_ac_c(this.pointer + 0x00);
        }
        
        private void _mpActor(fopAc_ac_c value) {
        }
        
        private cXyz _mPos() {
            return new cXyz(this.pointer + 0x04);
        }
        
        private void _mPos(cXyz value) {
        }
        
        private u32 _mMsgID() {
            return Memory.RAM.ReadU32(this.pointer + 0x10);
        }
        
        private void _mMsgID(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x10, value);
        }
        
        private u32 _field_0x14() {
            return Memory.RAM.ReadU32(this.pointer + 0x14);
        }
        
        private void _field_0x14(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x14, value);
        }
        
        private u32 _field_0x18() {
            return Memory.RAM.ReadU32(this.pointer + 0x18);
        }
        
        private void _field_0x18(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x18, value);
        }
    }
}
