//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class fopMsg_prm_timer {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 mTimerMode {get => this._mTimerMode(); set => this._mTimerMode(value);}//;
        
        public u16 mLimitTimeMs {get => this._mLimitTimeMs(); set => this._mLimitTimeMs(value);}//;
        
        public u8 mShowType {get => this._mShowType(); set => this._mShowType(value);}//;
        
        public u8 mIconType {get => this._mIconType(); set => this._mIconType(value);}//;
        
        public cXy mTimerPos {get => this._mTimerPos(); set => this._mTimerPos(value);}//;
        
        public cXy mRupeePos {get => this._mRupeePos(); set => this._mRupeePos(value);}//;
        
        public fopMsg_prm_timer(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x34;
        }
        
        private u32 _mTimerMode() {
            return Memory.RAM.ReadU32(this.pointer + 0x1C);
        }
        
        private void _mTimerMode(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x1C, value);
        }
        
        private u16 _mLimitTimeMs() {
            return Memory.RAM.ReadU16(this.pointer + 0x20);
        }
        
        private void _mLimitTimeMs(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x20, value);
        }
        
        private u8 _mShowType() {
            return Memory.RAM.ReadU8(this.pointer + 0x22);
        }
        
        private void _mShowType(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x22, value);
        }
        
        private u8 _mIconType() {
            return Memory.RAM.ReadU8(this.pointer + 0x23);
        }
        
        private void _mIconType(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x23, value);
        }
        
        private cXy _mTimerPos() {
            return new cXy(this.pointer + 0x24);
        }
        
        private void _mTimerPos(cXy value) {
        }
        
        private cXy _mRupeePos() {
            return new cXy(this.pointer + 0x2C);
        }
        
        private void _mRupeePos(cXy value) {
        }
    }
}
