//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class fopMsgM_pane_alpha_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        //public J2DPane pane {get => this._pane(); set => this._pane(value);}//;
        
        public u8 mInitAlpha {get => this._mInitAlpha(); set => this._mInitAlpha(value);}//;
        
        public u8 mNowAlpha {get => this._mNowAlpha(); set => this._mNowAlpha(value);}//;
        
        public fopMsgM_pane_alpha_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
/*        private J2DPane _pane() {
            return new J2DPane(this.pointer + 0x00);
        }
        
        private void _pane(J2DPane value) {
        }*/
        
        private u8 _mInitAlpha() {
            return Memory.RAM.ReadU8(this.pointer + 0x04);
        }
        
        private void _mInitAlpha(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x04, value);
        }
        
        private u8 _mNowAlpha() {
            return Memory.RAM.ReadU8(this.pointer + 0x05);
        }
        
        private void _mNowAlpha(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x05, value);
        }
    }
}
