//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class msg_process_profile_definition {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        //public leaf_process_profile_definition mBase {get => this._mBase(); set => this._mBase(value);}//;
        
        public msg_method_class mSubMtd {get => this._mSubMtd(); set => this._mSubMtd(value);}//;
        
        public msg_process_profile_definition(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
/*        
        private leaf_process_profile_definition _mBase() {
            return new leaf_process_profile_definition(this.pointer + 0x00);
        }
        
        private void _mBase(leaf_process_profile_definition value) {
        }*/
        
        // Subclassmethods
        private msg_method_class _mSubMtd() {
            return new msg_method_class(this.pointer + 0x24);
        }
        
        private void _mSubMtd(msg_method_class value) {
        }
    }
}
