//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class kankyo_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 mBsType {get => this._mBsType(); set => this._mBsType(value);}//;
        
        //public create_tag_class mDwTg {get => this._mDwTg(); set => this._mDwTg(value);}//;
        
        public kankyo_method_class mSubMtd {get => this._mSubMtd(); set => this._mSubMtd(value);}//;
        
        public cXyz mPos {get => this._mPos(); set => this._mPos(value);}//;
        
        public cXyz mScale {get => this._mScale(); set => this._mScale(value);}//;
        
        public u32 mParam {get => this._mParam(); set => this._mParam(value);}//;
        
        public kankyo_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u32 _mBsType() {
            return Memory.RAM.ReadU32(this.pointer + 0xC0);
        }
        
        private void _mBsType(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0xC0, value);
        }
/*        
        private create_tag_class _mDwTg() {
            return new create_tag_class(this.pointer + 0xC4);
        }
        
        private void _mDwTg(create_tag_class value) {
        }
        */
        private kankyo_method_class _mSubMtd() {
            return new kankyo_method_class(this.pointer + 0xD8);
        }
        
        private void _mSubMtd(kankyo_method_class value) {
        }
        
        private cXyz _mPos() {
            return new cXyz(this.pointer + 0xDC);
        }
        
        private void _mPos(cXyz value) {
        }
        
        private cXyz _mScale() {
            return new cXyz(this.pointer + 0xE8);
        }
        
        private void _mScale(cXyz value) {
        }
        
        private u32 _mParam() {
            return Memory.RAM.ReadU32(this.pointer + 0xF4);
        }
        
        private void _mParam(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0xF4, value);
        }
    }
}
