//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class kankyo_process_profile_definition {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;

        //public leaf_process_profile_definition _base {get => this.__base(); set => this.__base(value);}//;

        public kankyo_method_class mSubMtd {get => this._mSubMtd(); set => this._mSubMtd(value);}//;
        
        public kankyo_process_profile_definition(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x28;
        }
        /*        
        private leaf_process_profile_definition __base() {
            return new leaf_process_profile_definition(this.pointer + 0x00);
        }

        private void __base(leaf_process_profile_definition value) {
        }
                */
        private kankyo_method_class _mSubMtd() {
            return new kankyo_method_class(this.pointer + 0x24);
        }
        
        private void _mSubMtd(kankyo_method_class value) {
        }
    }
}
