//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dSv_player_status_a_c  {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u16 mMaxLife {get => this._mMaxLife(); set => this._mMaxLife(value);}//;
        
        public u16 mLife {get => this._mLife(); set => this._mLife(value);}//;
        
        public u16 mRupee {get => this._mRupee(); set => this._mRupee(value);}//;
        
        public u16 field_0x6 {get => this._field_0x6(); set => this._field_0x6(value);}//;
        
        public u8 field_0x8 {get => this._field_0x8(); set => this._field_0x8(value);}//;
        
        public u8[] mSelectItem {get => this._mSelectItem(); set => this._mSelectItem(value);}//;
        
        public u8[] mSelectEquip {get => this._mSelectEquip(); set => this._mSelectEquip(value);}//;
        
        public u8 mWalletSize {get => this._mWalletSize(); set => this._mWalletSize(value);}//;
        
        public u8 mMaxMagic {get => this._mMaxMagic(); set => this._mMaxMagic(value);}//;
        
        public u8 mMagic {get => this._mMagic(); set => this._mMagic(value);}//;
        
        public u8 field_0x15 {get => this._field_0x15(); set => this._field_0x15(value);}//;
        
        public u8 field_0x16 {get => this._field_0x16(); set => this._field_0x16(value);}//;
        
        public dSv_player_status_a_c (u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x18;
        }
        
        private u16 _mMaxLife() {
            return Memory.RAM.ReadU16(this.pointer + 0x00);
        }
        
        private void _mMaxLife(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x00, value);
        }
        
        private u16 _mLife() {
            return Memory.RAM.ReadU16(this.pointer + 0x02);
        }
        
        private void _mLife(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x02, value);
        }
        
        private u16 _mRupee() {
            return Memory.RAM.ReadU16(this.pointer + 0x04);
        }
        
        private void _mRupee(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x04, value);
        }
        
        private u16 _field_0x6() {
            return Memory.RAM.ReadU16(this.pointer + 0x06);
        }
        
        private void _field_0x6(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x06, value);
        }
        
        private u8 _field_0x8() {
            return Memory.RAM.ReadU8(this.pointer + 0x08);
        }
        
        private void _field_0x8(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x08, value);
        }
        
        // #ARRCOUNT 5
        private u8[] _mSelectItem() {
            u8[] bytes = new u8[5]; for(u32 i = 0; i < 5; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x09 + (i * 1));} return bytes;
        }
        
        private void _mSelectItem(u8[] value) {
            for(u32 i = 0; i < 5; i++){Memory.RAM.WriteU8(this.pointer + 0x09 + (i * 1), value[i]);}
        }
        
        // #ARRCOUNT 4
        private u8[] _mSelectEquip() {
            u8[] bytes = new u8[4]; for(u32 i = 0; i < 4; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x0E + (i * 1));} return bytes;
        }
        
        private void _mSelectEquip(u8[] value) {
            for(u32 i = 0; i < 4; i++){Memory.RAM.WriteU8(this.pointer + 0x0E + (i * 1), value[i]);}
        }
        
        private u8 _mWalletSize() {
            return Memory.RAM.ReadU8(this.pointer + 0x12);
        }
        
        private void _mWalletSize(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x12, value);
        }
        
        private u8 _mMaxMagic() {
            return Memory.RAM.ReadU8(this.pointer + 0x13);
        }
        
        private void _mMaxMagic(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x13, value);
        }
        
        private u8 _mMagic() {
            return Memory.RAM.ReadU8(this.pointer + 0x14);
        }
        
        private void _mMagic(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x14, value);
        }
        
        private u8 _field_0x15() {
            return Memory.RAM.ReadU8(this.pointer + 0x15);
        }
        
        private void _field_0x15(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x15, value);
        }
        
        private u8 _field_0x16() {
            return Memory.RAM.ReadU8(this.pointer + 0x16);
        }
        
        private void _field_0x16(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x16, value);
        }
    }
}
