//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dSv_event_c  {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u8[] mFlags {get => this._mFlags(); set => this._mFlags(value);}//;
        
        public dSv_event_c (u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x100;
        }
        
        // #ARRCOUNT 0x100
        private u8[] _mFlags() {
            u8[] bytes = new u8[0x100]; for(u32 i = 0; i < 0x100; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x0 + (i * 1));} return bytes;
        }
        
        private void _mFlags(u8[] value) {
            for(u32 i = 0; i < 0x100; i++){Memory.RAM.WriteU8(this.pointer + 0x0 + (i * 1), value[i]);}
        }
    }
}
