//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dSv_memory_c  {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public dSv_memBit_c mMembit {get => this._mMembit(); set => this._mMembit(value);}//;
        
        public dSv_memory_c (u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x24;
        }
        
        private dSv_memBit_c _mMembit() {
            return new dSv_memBit_c(this.pointer + 0x0);
        }
        
        private void _mMembit(dSv_memBit_c value) {
        }
    }
}
