//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dSv_turnRestart_c  {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public cXyz mPosition {get => this._mPosition(); set => this._mPosition(value);}//;
        
        public u32 mParam {get => this._mParam(); set => this._mParam(value);}//;
        
        public s16 mAngleY {get => this._mAngleY(); set => this._mAngleY(value);}//;
        
        public s8 mRoomNo {get => this._mRoomNo(); set => this._mRoomNo(value);}//;
        
        public u8 field_0x13 {get => this._field_0x13(); set => this._field_0x13(value);}//;
        
        public u8[] field_0x14 {get => this._field_0x14(); set => this._field_0x14(value);}//;
        
        public cXyz mShipPos {get => this._mShipPos(); set => this._mShipPos(value);}//;
        
        public s16 mShipAngleY {get => this._mShipAngleY(); set => this._mShipAngleY(value);}//;
        
        public u32 field_0x34 {get => this._field_0x34(); set => this._field_0x34(value);}//;
        
        public dSv_turnRestart_c (u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x38;
        }
        
        private cXyz _mPosition() {
            return new cXyz(this.pointer + 0x00);
        }
        
        private void _mPosition(cXyz value) {
        }
        
        private u32 _mParam() {
            return Memory.RAM.ReadU32(this.pointer + 0x0C);
        }
        
        private void _mParam(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x0C, value);
        }
        
        private s16 _mAngleY() {
            return Memory.RAM.ReadS16(this.pointer + 0x10);
        }
        
        private void _mAngleY(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x10, value);
        }
        
        private s8 _mRoomNo() {
            return Memory.RAM.ReadS8(this.pointer + 0x12);
        }
        
        private void _mRoomNo(s8 value) {
            Memory.RAM.WriteS8(this.pointer + 0x12, value);
        }
        
        private u8 _field_0x13() {
            return Memory.RAM.ReadU8(this.pointer + 0x13);
        }
        
        private void _field_0x13(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x13, value);
        }
        
        // #ARRCOUNT 0x10
        private u8[] _field_0x14() {
            u8[] bytes = new u8[0x10]; for(u32 i = 0; i < 0x10; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x14 + (i * 1));} return bytes;
        }
        
        private void _field_0x14(u8[] value) {
            for(u32 i = 0; i < 0x10; i++){Memory.RAM.WriteU8(this.pointer + 0x14 + (i * 1), value[i]);}
        }
        
        private cXyz _mShipPos() {
            return new cXyz(this.pointer + 0x24);
        }
        
        private void _mShipPos(cXyz value) {
        }
        
        private s16 _mShipAngleY() {
            return Memory.RAM.ReadS16(this.pointer + 0x30);
        }
        
        private void _mShipAngleY(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x30, value);
        }
        
        private u32 _field_0x34() {
            return Memory.RAM.ReadU32(this.pointer + 0x34);
        }
        
        private void _field_0x34(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x34, value);
        }
    }
}
