//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dSv_player_item_max_c  {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public dSv_player_item_max2_c mItemMax2 {get => this._mItemMax2(); set => this._mItemMax2(value);}//;
        
        public u8[] field_0x3 {get => this._field_0x3(); set => this._field_0x3(value);}//;
        
        public dSv_player_item_max_c (u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x8;
        }
        
        private dSv_player_item_max2_c _mItemMax2() {
            return new dSv_player_item_max2_c(this.pointer + 0x0);
        }
        
        private void _mItemMax2(dSv_player_item_max2_c value) {
        }
        
        // #ARRCOUNT 5
        private u8[] _field_0x3() {
            u8[] bytes = new u8[5]; for(u32 i = 0; i < 5; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x3 + (i * 1));} return bytes;
        }
        
        private void _field_0x3(u8[] value) {
            for(u32 i = 0; i < 5; i++){Memory.RAM.WriteU8(this.pointer + 0x3 + (i * 1), value[i]);}
        }
    }
}
