//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dSv_info_c  {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public dSv_save_c mSavedata {get => this._mSavedata(); set => this._mSavedata(value);}//;
        
        public dSv_memory_c mMemory {get => this._mMemory(); set => this._mMemory(value);}//;
        
        public dSv_danBit_c mDan {get => this._mDan(); set => this._mDan(value);}//;
        
        public dSv_zone_c[] mZone {get => this._mZone(); set => this._mZone(value);}//;
        
        public dSv_restart_c mRestart {get => this._mRestart(); set => this._mRestart(value);}//;
        
        public dSv_event_c mTmp {get => this._mTmp(); set => this._mTmp(value);}//;
        
        public dSv_turnRestart_c mTurnRestart {get => this._mTurnRestart(); set => this._mTurnRestart(value);}//;
        
        public u8 field_0x1290 {get => this._field_0x1290(); set => this._field_0x1290(value);}//;
        
        public u8 field_0x1291 {get => this._field_0x1291(); set => this._field_0x1291(value);}//;
        
        public u8 field_0x1292 {get => this._field_0x1292(); set => this._field_0x1292(value);}//;
        
        public s64 field_0x1298 {get => this._field_0x1298(); set => this._field_0x1298(value);}//;
        
        public dSv_info_c (u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x12A0;
        }
        
        private dSv_save_c _mSavedata() {
            return new dSv_save_c(this.pointer + 0x0000);
        }
        
        private void _mSavedata(dSv_save_c value) {
        }
        
        private dSv_memory_c _mMemory() {
            return new dSv_memory_c(this.pointer + 0x0778);
        }
        
        private void _mMemory(dSv_memory_c value) {
        }
        
        private dSv_danBit_c _mDan() {
            return new dSv_danBit_c(this.pointer + 0x079C);
        }
        
        private void _mDan(dSv_danBit_c value) {
        }
        
        // #ARRCOUNT 0x20
        private dSv_zone_c[] _mZone() {
          dSv_zone_c[] substructs = new dSv_zone_c[0x20]; for(u32 i = 0; i < 0x20; i++){substructs[i] = new dSv_zone_c(this.pointer + 0x07A8 + (i * dSv_zone_c.getSize()));}; return substructs;
        }
        
        private void _mZone(dSv_zone_c[] value) {
        }
        
        private dSv_restart_c _mRestart() {
            return new dSv_restart_c(this.pointer + 0x1128);
        }
        
        private void _mRestart(dSv_restart_c value) {
        }
        
        private dSv_event_c _mTmp() {
            return new dSv_event_c(this.pointer + 0x1158);
        }
        
        private void _mTmp(dSv_event_c value) {
        }
        
        private dSv_turnRestart_c _mTurnRestart() {
            return new dSv_turnRestart_c(this.pointer + 0x1258);
        }
        
        private void _mTurnRestart(dSv_turnRestart_c value) {
        }
        
        private u8 _field_0x1290() {
            return Memory.RAM.ReadU8(this.pointer + 0x1290);
        }
        
        private void _field_0x1290(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1290, value);
        }
        
        private u8 _field_0x1291() {
            return Memory.RAM.ReadU8(this.pointer + 0x1291);
        }
        
        private void _field_0x1291(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1291, value);
        }
        
        private u8 _field_0x1292() {
            return Memory.RAM.ReadU8(this.pointer + 0x1292);
        }
        
        private void _field_0x1292(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1292, value);
        }
        
        private s64 _field_0x1298() {
            return Memory.RAM.ReadS64(this.pointer + 0x1298);
        }
        
        private void _field_0x1298(s64 value) {
            Memory.RAM.WriteS64(this.pointer + 0x1298, value);
        }
    }
}
