//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class fopKyM_prm_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public cXyz mPos {get => this._mPos(); set => this._mPos(value);}//;
        
        public cXyz mScale {get => this._mScale(); set => this._mScale(value);}//;
        
        public u32 mParam {get => this._mParam(); set => this._mParam(value);}//;
        
        public fopKyM_prm_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x1C;
        }
        
        private cXyz _mPos() {
            return new cXyz(this.pointer + 0x00);
        }
        
        private void _mPos(cXyz value) {
        }
        
        private cXyz _mScale() {
            return new cXyz(this.pointer + 0x0C);
        }
        
        private void _mScale(cXyz value) {
        }
        
        private u32 _mParam() {
            return Memory.RAM.ReadU32(this.pointer + 0x18);
        }
        
        private void _mParam(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x18, value);
        }
    }
}
