//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class daPy_swimTailEcallBack_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
       // public bool field_0x04 {get => this._field_0x04(); set => this._field_0x04(value);}//;
        
        //public bool field_0x05 {get => this._field_0x05(); set => this._field_0x05(value);}//;
        
        public f32 field_0x08 {get => this._field_0x08(); set => this._field_0x08(value);}//;
        
        public f32 field_0x0C {get => this._field_0x0C(); set => this._field_0x0C(value);}//;
        
        public f32 field_0x10 {get => this._field_0x10(); set => this._field_0x10(value);}//;
        
        public cXyz field_0x14 {get => this._field_0x14(); set => this._field_0x14(value);}//;
        
        public u32 field_0x20 {get => this._field_0x20(); set => this._field_0x20(value);}//;
        
        //public JPABaseEmitter mpEmitter {get => this._mpEmitter(); set => this._mpEmitter(value);}//;
        
        public daPy_swimTailEcallBack_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x28;
        }
        
/*        private bool _field_0x04() {
            return new bool(this.pointer + 0x04);
        }
        
        private void _field_0x04(bool value) {
        }
        
        private bool _field_0x05() {
            return new bool(this.pointer + 0x05);
        }
        
        private void _field_0x05(bool value) {
        }
        */
        private f32 _field_0x08() {
            return Memory.RAM.ReadF32(this.pointer + 0x08);
        }
        
        private void _field_0x08(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x08, value);
        }
        
        private f32 _field_0x0C() {
            return Memory.RAM.ReadF32(this.pointer + 0x0C);
        }
        
        private void _field_0x0C(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x0C, value);
        }
        
        private f32 _field_0x10() {
            return Memory.RAM.ReadF32(this.pointer + 0x10);
        }
        
        private void _field_0x10(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x10, value);
        }
        
        private cXyz _field_0x14() {
            return new cXyz(this.pointer + 0x14);
        }
        
        private void _field_0x14(cXyz value) {
        }
        
        private u32 _field_0x20() {
            return Memory.RAM.ReadU32(this.pointer + 0x20);
        }
        
        private void _field_0x20(u32 value) {
        }
        
/*        private JPABaseEmitter _mpEmitter() {
            return new JPABaseEmitter(this.pointer + 0x24);
        }
        
        private void _mpEmitter(JPABaseEmitter value) {
        }*/
    }
}
