//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class daPy_matAnm_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public cXy mEyePosOld {get => this._mEyePosOld(); set => this._mEyePosOld(value);}//;
        
        public cXy mEyePos {get => this._mEyePos(); set => this._mEyePos(value);}//;
        
        public daPy_matAnm_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x7C;
        }
        
        private cXy _mEyePosOld() {
            return new cXy(this.pointer + 0x6C);
        }
        
        private void _mEyePosOld(cXy value) {
        }
        
        private cXy _mEyePos() {
            return new cXy(this.pointer + 0x74);
        }
        
        private void _mEyePos(cXy value) {
        }
    }
}
