//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class daPy_footData_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u8[] field_0x000 {get => this._field_0x000(); set => this._field_0x000(value);}//;
        
        //public dBgS_LinkGndChk field_0x034 {get => this._field_0x034(); set => this._field_0x034(value);}//;
        
        public u8[] field_0x088 {get => this._field_0x088(); set => this._field_0x088(value);}//;
        
        public daPy_footData_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        // #ARRCOUNT 52
        private u8[] _field_0x000() {
            u8[] bytes = new u8[52]; for(u32 i = 0; i < 52; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x000 + (i * 1));} return bytes;
        }
        
        private void _field_0x000(u8[] value) {
            for(u32 i = 0; i < 52; i++){Memory.RAM.WriteU8(this.pointer + 0x000 + (i * 1), value[i]);}
        }
/*        
        private dBgS_LinkGndChk _field_0x034() {
            return new dBgS_LinkGndChk(this.pointer + 0x034);
        }
        
        private void _field_0x034(dBgS_LinkGndChk value) {
        }*/
        
        // #ARRCOUNT 144
        private u8[] _field_0x088() {
            u8[] bytes = new u8[144]; for(u32 i = 0; i < 144; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x088 + (i * 1));} return bytes;
        }
        
        private void _field_0x088(u8[] value) {
            for(u32 i = 0; i < 144; i++){Memory.RAM.WriteU8(this.pointer + 0x088 + (i * 1), value[i]);}
        }
    }
}
