//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class daPy_swBlur_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        //public ResTIMG mpTex {get => this._mpTex(); set => this._mpTex(value);}//;
        
        public u32 field_0x014 {get => this._field_0x014(); set => this._field_0x014(value);}//;
        
        public u32 field_0x018 {get => this._field_0x018(); set => this._field_0x018(value);}//;
        
        public u32 mBlurColorType {get => this._mBlurColorType(); set => this._mBlurColorType(value);}//;
        
        public f32 field_0x020 {get => this._field_0x020(); set => this._field_0x020(value);}//;
        
        public u32 mpPosBuffer {get => this._mpPosBuffer(); set => this._mpPosBuffer(value);}//;
        
        public cXyz field_0x028 {get => this._field_0x028(); set => this._field_0x028(value);}//;
        
        public cXyz[] field_0x034 {get => this._field_0x034(); set => this._field_0x034(value);}//;
        
        public cXyz[] field_0x304 {get => this._field_0x304(); set => this._field_0x304(value);}//;
        
        public daPy_swBlur_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        /*private ResTIMG _mpTex() {
            return new ResTIMG(this.pointer + 0x010);
        }
        
        private void _mpTex(ResTIMG value) {
        }*/
        
        private u32 _field_0x014() {
            return Memory.RAM.ReadU32(this.pointer + 0x014);
        }
        
        private void _field_0x014(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x014, value);
        }
        
        private u32 _field_0x018() {
            return Memory.RAM.ReadU32(this.pointer + 0x018);
        }
        
        private void _field_0x018(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x018, value);
        }
        
        private u32 _mBlurColorType() {
            return Memory.RAM.ReadU32(this.pointer + 0x01C);
        }
        
        private void _mBlurColorType(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x01C, value);
        }
        
        private f32 _field_0x020() {
            return Memory.RAM.ReadF32(this.pointer + 0x020);
        }
        
        private void _field_0x020(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x020, value);
        }
        
        private u32 _mpPosBuffer() {
            return Memory.RAM.ReadU32(this.pointer + 0x024);
        }
        
        private void _mpPosBuffer(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x024, value);
        }
        
        private cXyz _field_0x028() {
            return new cXyz(this.pointer + 0x028);
        }
        
        private void _field_0x028(cXyz value) {
        }
        
        // #ARRCOUNT 60
        private cXyz[] _field_0x034() {
          cXyz[] substructs = new cXyz[60]; for(u32 i = 0; i < 60; i++){substructs[i] = new cXyz(this.pointer + 0x034 + (i * cXyz.getSize()));}; return substructs;
        }
        
        private void _field_0x034(cXyz[] value) {
        }
        
        // #ARRCOUNT 60
        private cXyz[] _field_0x304() {
          cXyz[] substructs = new cXyz[60]; for(u32 i = 0; i < 60; i++){substructs[i] = new cXyz(this.pointer + 0x304 + (i * cXyz.getSize()));}; return substructs;
        }
        
        private void _field_0x304(cXyz[] value) {
        }
    }
}
