//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class daPy_anmIndex_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u16 mUnderBckIdx {get => this._mUnderBckIdx(); set => this._mUnderBckIdx(value);}//;
        
        public u16 mUpperBckIdx {get => this._mUpperBckIdx(); set => this._mUpperBckIdx(value);}//;
        
        public daPy_anmIndex_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u16 _mUnderBckIdx() {
            return Memory.RAM.ReadU16(this.pointer + 0x00);
        }
        
        private void _mUnderBckIdx(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x00, value);
        }
        
        private u16 _mUpperBckIdx() {
            return Memory.RAM.ReadU16(this.pointer + 0x02);
        }
        
        private void _mUpperBckIdx(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x02, value);
        }
    }
}
