//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class daPy_anmHeap_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u16 mIdx {get => this._mIdx(); set => this._mIdx(value);}//;
        
        public u16 field_0x2 {get => this._field_0x2(); set => this._field_0x2(value);}//;
        
        public u16 field_0x4 {get => this._field_0x4(); set => this._field_0x4(value);}//;
        
        public u16 field_0x6 {get => this._field_0x6(); set => this._field_0x6(value);}//;
        
        public u32 m_buffer {get => this._m_buffer(); set => this._m_buffer(value);}//;
        
        //public JKRSolidHeap mpAnimeHeap {get => this._mpAnimeHeap(); set => this._mpAnimeHeap(value);}//;
        
        public daPy_anmHeap_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u16 _mIdx() {
            return Memory.RAM.ReadU16(this.pointer + 0x0);
        }
        
        private void _mIdx(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x0, value);
        }
        
        private u16 _field_0x2() {
            return Memory.RAM.ReadU16(this.pointer + 0x2);
        }
        
        private void _field_0x2(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x2, value);
        }
        
        private u16 _field_0x4() {
            return Memory.RAM.ReadU16(this.pointer + 0x4);
        }
        
        private void _field_0x4(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x4, value);
        }
        
        private u16 _field_0x6() {
            return Memory.RAM.ReadU16(this.pointer + 0x6);
        }
        
        private void _field_0x6(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x6, value);
        }
        
        private u32 _m_buffer() {
            return Memory.RAM.ReadU32(this.pointer + 0x8);
        }
        
        private void _m_buffer(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x8, value);
        }
        
/*        private JKRSolidHeap _mpAnimeHeap() {
            return new JKRSolidHeap(this.pointer + 0xC);
        }
        
        private void _mpAnimeHeap(JKRSolidHeap value) {
        }*/
    }
}
