//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class daPy_dmEcallBack_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 csXyzmpAngle {get => this._csXyzmpAngle(); set => this._csXyzmpAngle(value);}//;
        
        public daPy_dmEcallBack_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x10;
        }
        
        private u32 _csXyzmpAngle() {
            return Memory.RAM.ReadU32(this.pointer + 0xC);
        }
        
        private void _csXyzmpAngle(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0xC, value);
        }
    }
}
