//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class daPy_aura_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        //public J3DModel mpYaura00Model {get => this._mpYaura00Model(); set => this._mpYaura00Model(value);}//;
        
        public f32 mFrame {get => this._mFrame(); set => this._mFrame(value);}//;
        
        public daPy_aura_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x08;
        }
/*        
        private J3DModel _mpYaura00Model() {
            return new J3DModel(this.pointer + 0x00);
        }
        
        private void _mpYaura00Model(J3DModel value) {
        }*/
        
        private f32 _mFrame() {
            return Memory.RAM.ReadF32(this.pointer + 0x04);
        }
        
        private void _mFrame(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x04, value);
        }
    }
}
