//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class daPy_waterDropEcallBack_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u8[] field_0x1C {get => this._field_0x1C(); set => this._field_0x1C(value);}//;
        
        public daPy_waterDropEcallBack_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x20;
        }
        
        // #ARRCOUNT 0x4
        private u8[] _field_0x1C() {
            u8[] bytes = new u8[0x4]; for(u32 i = 0; i < 0x4; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x1C + (i * 1));} return bytes;
        }
        
        private void _field_0x1C(u8[] value) {
            for(u32 i = 0; i < 0x4; i++){Memory.RAM.WriteU8(this.pointer + 0x1C + (i * 1), value[i]);}
        }
    }
}
