//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class daPy_actorKeep_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 mID {get => this._mID(); set => this._mID(value);}//;
        
        public fopAc_ac_c mActor {get => this._mActor(); set => this._mActor(value);}//;
        
        public daPy_actorKeep_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x8;
        }
        
        private u32 _mID() {
            return Memory.RAM.ReadU32(this.pointer + 0x0);
        }
        
        private void _mID(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x0, value);
        }
        
        private fopAc_ac_c _mActor() {
            return new fopAc_ac_c(this.pointer + 0x4);
        }
        
        private void _mActor(fopAc_ac_c value) {
        }
    }
}
