//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class daPy_footEffect_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        //public dPa_smokeEcallBack mSmokeCb {get => this._mSmokeCb(); set => this._mSmokeCb(value);}//;
        
        //public dPa_followEcallBack mFollowCb {get => this._mFollowCb(); set => this._mFollowCb(value);}//;
        
        public u8[] field_0x34 {get => this._field_0x34(); set => this._field_0x34(value);}//;
        
        public daPy_footEffect_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
/*        
        private dPa_smokeEcallBack _mSmokeCb() {
            return new dPa_smokeEcallBack(this.pointer + 0x00);
        }
        
        private void _mSmokeCb(dPa_smokeEcallBack value) {
        }
        
        private dPa_followEcallBack _mFollowCb() {
            return new dPa_followEcallBack(this.pointer + 0x20);
        }
        
        private void _mFollowCb(dPa_followEcallBack value) {

        }*/
        
        // #ARRCOUNT 24
        private u8[] _field_0x34() {
            u8[] bytes = new u8[24]; for(u32 i = 0; i < 24; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x34 + (i * 1));} return bytes;
        }
        
        private void _field_0x34(u8[] value) {
            for(u32 i = 0; i < 24; i++){Memory.RAM.WriteU8(this.pointer + 0x34 + (i * 1), value[i]);}
        }
    }
}
