//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class camera_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 field_0x23c {get => this._field_0x23c(); set => this._field_0x23c(value);}//;
        
        public u32 field_0x244 {get => this._field_0x244(); set => this._field_0x244(value);}//;
        
        //public dCamera_c mCamera {get => this._mCamera(); set => this._mCamera(value);}//;
        
        public camera_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u32 _field_0x23c() {
            return Memory.RAM.ReadU32(this.pointer + 0x23C);
        }
        
        private void _field_0x23c(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x23C, value);
        }
        
        private u32 _field_0x244() {
            return Memory.RAM.ReadU32(this.pointer + 0x240);
        }
        
        private void _field_0x244(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x240, value);
        }
/*        
        private dCamera_c _mCamera() {
            return new dCamera_c(this.pointer + 0x244);
        }
        
        private void _mCamera(dCamera_c value) {
        }*/
    }
}
