//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class fopAcM_prmScale_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u8 x {get => this._x(); set => this._x(value);}//;
        
        public u8 y {get => this._y(); set => this._y(value);}//;
        
        public u8 z {get => this._z(); set => this._z(value);}//;
        
        public fopAcM_prmScale_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u8 _x() {
            return Memory.RAM.ReadU8(this.pointer + 0x0); // DEADBEEF TODO: Fix Addr
        }
        
        private void _x(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x0, value);// DEADBEEF TODO: Fix Addr
        }
        
        private u8 _y() {
            return Memory.RAM.ReadU8(this.pointer + 0x0); // DEADBEEF TODO: Fix Addr
        }
        
        private void _y(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x0, value);// DEADBEEF TODO: Fix Addr
        }
        
        private u8 _z() {
            return Memory.RAM.ReadU8(this.pointer + 0x0); // DEADBEEF TODO: Fix Addr
        }
        
        private void _z(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x0, value);// DEADBEEF TODO: Fix Addr
        }
    }
}
