//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class fopAcM_prmBase_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 field_0x00 {get => this._field_0x00(); set => this._field_0x00(value);}//;
        
        public cXyz field_0x04 {get => this._field_0x04(); set => this._field_0x04(value);}//;
        
        public csXyz field_0x10 {get => this._field_0x10(); set => this._field_0x10(value);}//;
        
        public u16 field_0x16 {get => this._field_0x16(); set => this._field_0x16(value);}//;
        
        public u32 mParameter {get => this._mParameter(); set => this._mParameter(value);}//;
        
        public cXyz mPos {get => this._mPos(); set => this._mPos(value);}//;
        
        public csXyz mAngle {get => this._mAngle(); set => this._mAngle(value);}//;
        
        public u16 mSetId {get => this._mSetId(); set => this._mSetId(value);}//;
        
        public fopAcM_prmScale_class mScale {get => this._mScale(); set => this._mScale(value);}//;
        
        public u8 mGbaName {get => this._mGbaName(); set => this._mGbaName(value);}//;
        
        public s32 mParentPcId {get => this._mParentPcId(); set => this._mParentPcId(value);}//;
        
        public s8 mSubtype {get => this._mSubtype(); set => this._mSubtype(value);}//;
        
        public s8 mRoomNo {get => this._mRoomNo(); set => this._mRoomNo(value);}//;
        
        public fopAcM_prmBase_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u32 _field_0x00() {
            return Memory.RAM.ReadU32(this.pointer + 0x00);
        }
        
        private void _field_0x00(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x00, value);
        }
        
        private cXyz _field_0x04() {
            return new cXyz(this.pointer + 0x04);
        }
        
        private void _field_0x04(cXyz value) {
        }
        
        private csXyz _field_0x10() {
            return new csXyz(this.pointer + 0x10);
        }
        
        private void _field_0x10(csXyz value) {
        }
        
        private u16 _field_0x16() {
            return Memory.RAM.ReadU16(this.pointer + 0x16);
        }
        
        private void _field_0x16(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x16, value);
        }
        
        // singleU32Parameter
        private u32 _mParameter() {
            return Memory.RAM.ReadU32(this.pointer + 0x00);
        }
        
        private void _mParameter(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x00, value);
        }
        
        private cXyz _mPos() {
            return new cXyz(this.pointer + 0x04);
        }
        
        private void _mPos(cXyz value) {
        }
        
        // rotation
        private csXyz _mAngle() {
            return new csXyz(this.pointer + 0x10);
        }
        
        private void _mAngle(csXyz value) {
        }
        
        private u16 _mSetId() {
            return Memory.RAM.ReadU16(this.pointer + 0x16);
        }
        
        private void _mSetId(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x16, value);
        }
        
        private fopAcM_prmScale_class _mScale() {
            return new fopAcM_prmScale_class(this.pointer + 0x18);
        }
        
        private void _mScale(fopAcM_prmScale_class value) {
        }
        
        private u8 _mGbaName() {
            return Memory.RAM.ReadU8(this.pointer + 0x1B);
        }
        
        private void _mGbaName(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1B, value);
        }
        
        // parentprocessID
        private s32 _mParentPcId() {
            return Memory.RAM.ReadS32(this.pointer + 0x1C);
        }
        
        private void _mParentPcId(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x1C, value);
        }
        
        private s8 _mSubtype() {
            return Memory.RAM.ReadS8(this.pointer + 0x20);
        }
        
        private void _mSubtype(s8 value) {
            Memory.RAM.WriteS8(this.pointer + 0x20, value);
        }
        
        private s8 _mRoomNo() {
            return Memory.RAM.ReadS8(this.pointer + 0x21);
        }
        
        private void _mRoomNo(s8 value) {
            Memory.RAM.WriteS8(this.pointer + 0x21, value);
        }
    }
}
