//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class fopAcM_search_prm {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 mpProcName {get => this._mpProcName(); set => this._mpProcName(value);}//;
        
        public u32 mParamMask {get => this._mParamMask(); set => this._mParamMask(value);}//;
        
        public u32 mParameter {get => this._mParameter(); set => this._mParameter(value);}//;
        
        public fopAcM_search_prm(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u32 _mpProcName() {
            return Memory.RAM.ReadU32(this.pointer + 0x00);
        }
        
        private void _mpProcName(u32 value) {
        }
        
        private u32 _mParamMask() {
            return Memory.RAM.ReadU32(this.pointer + 0x04);
        }
        
        private void _mParamMask(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x04, value);
        }
        
        private u32 _mParameter() {
            return Memory.RAM.ReadU32(this.pointer + 0x08);
        }
        
        private void _mParameter(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x08, value);
        }
    }
}
