//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class overlap_task_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public overlap_method_class mSubMtd {get => this._mSubMtd(); set => this._mSubMtd(value);}//;
        
        //public request_base_class mRq {get => this._mRq(); set => this._mRq(value);}//;
        
        public u32 mScenePId {get => this._mScenePId(); set => this._mScenePId(value);}//;
        
        public overlap_task_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0xCC;
        }
        
        private overlap_method_class _mSubMtd() {
            return new overlap_method_class(this.pointer + 0xC0);
        }
        
        private void _mSubMtd(overlap_method_class value) {
        }
/*        
        private request_base_class _mRq() {
            return new request_base_class(this.pointer + 0xC4);
        }
        
        private void _mRq(request_base_class value) {
        }
        */
        private u32 _mScenePId() {
            return Memory.RAM.ReadU32(this.pointer + 0xC8);
        }
        
        private void _mScenePId(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0xC8, value);
        }
    }
}
