//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class lookat_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public cXyz mEye {get => this._mEye(); set => this._mEye(value);}//;
        
        public cXyz mCenter {get => this._mCenter(); set => this._mCenter(value);}//;
        
        public cXyz mUp {get => this._mUp(); set => this._mUp(value);}//;
        
        public lookat_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private cXyz _mEye() {
            return new cXyz(this.pointer + 0x00);
        }
        
        private void _mEye(cXyz value) {
        }
        
        private cXyz _mCenter() {
            return new cXyz(this.pointer + 0x0C);
        }
        
        private void _mCenter(cXyz value) {
        }
        
        private cXyz _mUp() {
            return new cXyz(this.pointer + 0x18);
        }
        
        private void _mUp(cXyz value) {
        }
    }
}
