//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class actor_method_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        //public leafdraw_method_class _base {get => this._base(); set => this._base(value);}//;
        
        public u8[] field_0x14 {get => this._field_0x14(); set => this._field_0x14(value);}//;
        
        public actor_method_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
/*        private leafdraw_method_class _base() {
            return new leafdraw_method_class(this.pointer + 0x00);
        }
        
        private void _base(leafdraw_method_class value) {
        }*/
        
        // #ARRCOUNT 0xC
        // Likelypadding
        private u8[] _field_0x14() {
            u8[] bytes = new u8[0xC]; for(u32 i = 0; i < 0xC; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x14 + (i * 1));} return bytes;
        }
        
        private void _field_0x14(u8[] value) {
            for(u32 i = 0; i < 0xC; i++){Memory.RAM.WriteU8(this.pointer + 0x14 + (i * 1), value[i]);}
        }
    }
}
