//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dEvt_info_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u16 mCommand {get => this._mCommand(); set => this._mCommand(value);}//;
        
        public u16 mCondition {get => this._mCondition(); set => this._mCondition(value);}//;
        
        public s16 mEventId {get => this._mEventId(); set => this._mEventId(value);}//;
        
        public u8 mMapToolId {get => this._mMapToolId(); set => this._mMapToolId(value);}//;
        
        public s8 mIndex {get => this._mIndex(); set => this._mIndex(value);}//;
        
        /*public CallbackFunc mpEventCB {get => this._mpEventCB(); set => this._mpEventCB(value);}//;
        
        public CallbackFunc mpCheckCB {get => this._mpCheckCB(); set => this._mpCheckCB(value);}//;
        
        public CallbackFunc mpPhotoCB {get => this._mpPhotoCB(); set => this._mpPhotoCB(value);}//;*/
        
        public cXyz pos {get => this._pos(); set => this._pos(value);}//;
        
        public csXyz angle {get => this._angle(); set => this._angle(value);}//;
        
        public s8 roomNo {get => this._roomNo(); set => this._roomNo(value);}//;
        
        public u8 field_0x13 {get => this._field_0x13(); set => this._field_0x13(value);}//;
        
        public dEvt_info_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u16 _mCommand() {
            return Memory.RAM.ReadU16(this.pointer + 0x04);
        }
        
        private void _mCommand(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x04, value);
        }
        
        private u16 _mCondition() {
            return Memory.RAM.ReadU16(this.pointer + 0x06);
        }
        
        private void _mCondition(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x06, value);
        }
        
        private s16 _mEventId() {
            return Memory.RAM.ReadS16(this.pointer + 0x08);
        }
        
        private void _mEventId(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x08, value);
        }
        
        private u8 _mMapToolId() {
            return Memory.RAM.ReadU8(this.pointer + 0x0A);
        }
        
        private void _mMapToolId(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x0A, value);
        }
        
        private s8 _mIndex() {
            return Memory.RAM.ReadS8(this.pointer + 0x0B);
        }
        
        private void _mIndex(s8 value) {
            Memory.RAM.WriteS8(this.pointer + 0x0B, value);
        }
        
        /*private CallbackFunc _mpEventCB() {
            return new CallbackFunc(this.pointer + 0x0C);
        }
        
        private void _mpEventCB(CallbackFunc value) {
        }
        
        private CallbackFunc _mpCheckCB() {
            return new CallbackFunc(this.pointer + 0x10);
        }
        
        private void _mpCheckCB(CallbackFunc value) {
        }
        
        private CallbackFunc _mpPhotoCB() {
            return new CallbackFunc(this.pointer + 0x14);
        }
        
        private void _mpPhotoCB(CallbackFunc value) {
        }*/
        
        private cXyz _pos() {
            return new cXyz(this.pointer + 0x00);
        }
        
        private void _pos(cXyz value) {
        }
        
        private csXyz _angle() {
            return new csXyz(this.pointer + 0x0C);
        }
        
        private void _angle(csXyz value) {
        }
        
        private s8 _roomNo() {
            return Memory.RAM.ReadS8(this.pointer + 0x12);
        }
        
        private void _roomNo(s8 value) {
            Memory.RAM.WriteS8(this.pointer + 0x12, value);
        }
        
        private u8 _field_0x13() {
            return Memory.RAM.ReadU8(this.pointer + 0x13);
        }
        
        private void _field_0x13(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x13, value);
        }
    }
}
