//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class fopAc_ac_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 mAcType {get => this._mAcType(); set => this._mAcType(value);}//;
        
       // public create_tag_class mAcTg {get => this._mAcTg(); set => this._mAcTg(value);}//;
        
        //public create_tag_class mDwTg {get => this._mDwTg(); set => this._mDwTg(value);}//;
        
        public actor_method_class mSubMtd {get => this._mSubMtd(); set => this._mSubMtd(value);}//;
        
        //public JKRSolidHeap heap {get => this._heap(); set => this._heap(value);}//;
        
        public dEvt_info_c mEvtInfo {get => this._mEvtInfo(); set => this._mEvtInfo(value);}//;
        
        //public dKy_tevstr_c mTevStr {get => this._mTevStr(); set => this._mTevStr(value);}//;
        
        public u16 mSetId {get => this._mSetId(); set => this._mSetId(value);}//;
        
        public u8 mGroup {get => this._mGroup(); set => this._mGroup(value);}//;
        
        public u8 mCullType {get => this._mCullType(); set => this._mCullType(value);}//;
        
        public u8 mDemoActorId {get => this._mDemoActorId(); set => this._mDemoActorId(value);}//;
        
        public s8 mSubtype {get => this._mSubtype(); set => this._mSubtype(value);}//;
        
        public u8 mGbaName {get => this._mGbaName(); set => this._mGbaName(value);}//;
        
        public u32 mStatus {get => this._mStatus(); set => this._mStatus(value);}//;
        
        public u32 mCondition {get => this._mCondition(); set => this._mCondition(value);}//;
        
        public u32 mParentPcId {get => this._mParentPcId(); set => this._mParentPcId(value);}//;
        
        public actor_place home {get => this._home(); set => this._home(value);}//;
        
        public actor_place old {get => this._old(); set => this._old(value);}//;
        
        public actor_place current {get => this._current(); set => this._current(value);}//;
        
        public csXyz shape_angle {get => this._shape_angle(); set => this._shape_angle(value);}//;
        
        public cXyz mScale {get => this._mScale(); set => this._mScale(value);}//;
        
        public cXyz speed {get => this._speed(); set => this._speed(value);}//;
        
        //public MtxP mCullMtx {get => this._mCullMtx(); set => this._mCullMtx(value);}//;
        
        public fopAc_ac_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u32 _mAcType() {
            return Memory.RAM.ReadU32(this.pointer + 0x0C0);
        }
        
        private void _mAcType(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x0C0, value);
        }
        
        /*private create_tag_class _mAcTg() {
            return new create_tag_class(this.pointer + 0x0C4);
        }
        
        private void _mAcTg(create_tag_class value) {
        }
        
        private create_tag_class _mDwTg() {
            return new create_tag_class(this.pointer + 0x0D8);
        }
        
        private void _mDwTg(create_tag_class value) {
        }*/
        
        private actor_method_class _mSubMtd() {
            return new actor_method_class(Memory.RAM.ReadU32(this.pointer + 0x0EC));
        }
        
        private void _mSubMtd(actor_method_class value) {
        } 

        /*
        
        private JKRSolidHeap _heap() {
            return new JKRSolidHeap(this.pointer + 0x0F0);
        }
        
        private void _heap(JKRSolidHeap value) {
        }
        */
        private dEvt_info_c _mEvtInfo() {
            return new dEvt_info_c(this.pointer + 0x0F4);
        }
        
        private void _mEvtInfo(dEvt_info_c value) {
        }
        
       /* private dKy_tevstr_c _mTevStr() {
            return new dKy_tevstr_c(this.pointer + 0x10C);
        }
        
        private void _mTevStr(dKy_tevstr_c value) {
        }
        */
        private u16 _mSetId() {
            return Memory.RAM.ReadU16(this.pointer + 0x1BC);
        }
        
        private void _mSetId(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x1BC, value);
        }
        
        private u8 _mGroup() {
            return Memory.RAM.ReadU8(this.pointer + 0x1BE);
        }
        
        private void _mGroup(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1BE, value);
        }
        
        private u8 _mCullType() {
            return Memory.RAM.ReadU8(this.pointer + 0x1BF);
        }
        
        private void _mCullType(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1BF, value);
        }
        
        private u8 _mDemoActorId() {
            return Memory.RAM.ReadU8(this.pointer + 0x1C0);
        }
        
        private void _mDemoActorId(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1C0, value);
        }
        
        private s8 _mSubtype() {
            return Memory.RAM.ReadS8(this.pointer + 0x1C1);
        }
        
        private void _mSubtype(s8 value) {
            Memory.RAM.WriteS8(this.pointer + 0x1C1, value);
        }
        
        private u8 _mGbaName() {
            return Memory.RAM.ReadU8(this.pointer + 0x1C2);
        }
        
        private void _mGbaName(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1C2, value);
        }
        
        private u32 _mStatus() {
            return Memory.RAM.ReadU32(this.pointer + 0x1C4);
        }
        
        private void _mStatus(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x1C4, value);
        }
        
        private u32 _mCondition() {
            return Memory.RAM.ReadU32(this.pointer + 0x1C8);
        }
        
        private void _mCondition(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x1C8, value);
        }
        
        private u32 _mParentPcId() {
            return Memory.RAM.ReadU32(this.pointer + 0x1CC);
        }
        
        private void _mParentPcId(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x1CC, value);
        }
        
        private actor_place _home() {
            return new actor_place(this.pointer + 0x1D0);
        }
        
        private void _home(actor_place value) {
        }
        
        private actor_place _old() {
            return new actor_place(this.pointer + 0x1E4);
        }
        
        private void _old(actor_place value) {
        }
        
        private actor_place _current() {
            return new actor_place(this.pointer + 0x1F8);
        }
        
        private void _current(actor_place value) {
        }
        
        private csXyz _shape_angle() {
            return new csXyz(this.pointer + 0x20C);
        }
        
        private void _shape_angle(csXyz value) {
        }
        
        private cXyz _mScale() {
            return new cXyz(this.pointer + 0x214);
        }
        
        private void _mScale(cXyz value) {
        }
        
        private cXyz _speed() {
            return new cXyz(this.pointer + 0x220);
        }
        
        private void _speed(cXyz value) {
        }
        
       /* private MtxP _mCullMtx() {
            return new MtxP(this.pointer + 0x22C);
        }
        
        private void _mCullMtx(MtxP value) {
        }*/
    }
}
