//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class fopAc_cullSizeBox {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public cXyz mMin {get => this._mMin(); set => this._mMin(value);}//;
        
        public cXyz mMax {get => this._mMax(); set => this._mMax(value);}//;
        
        
        public fopAc_cullSizeBox(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }

        private cXyz _mMin() {
            return new cXyz(this.pointer + 0x0);
        }
        
        private void _mMin(cXyz value) {
        }
        
        private cXyz _mMax() {
            return new cXyz(this.pointer + 0xC);
        }
        
        private void _mMax(cXyz value) {
        }
        
    }
}
