//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class fopAc_cullSizeSphere {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;

        public cXyz mCenter {get => this._mCenter(); set => this._mCenter(value);}//;
        
        public f32 mRadius {get => this._mRadius(); set => this._mRadius(value);}//;
        
       
        public fopAc_cullSizeSphere(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }

        private cXyz _mCenter() {
            return new cXyz(this.pointer + 0x0);
        }
        
        private void _mCenter(cXyz value) {
        }
        
        private f32 _mRadius() {
            return Memory.RAM.ReadF32(this.pointer + 0xC);
        }
        
        private void _mRadius(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0xC, value);
        }
        
    }
}
