//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class fopEn_enemy_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public f32 m290 {get => this._m290(); set => this._m290(value);}//;
        
        public f32 m294 {get => this._m294(); set => this._m294(value);}//;
        
        public f32 m298 {get => this._m298(); set => this._m298(value);}//;
        
        public f32 m29C {get => this._m29C(); set => this._m29C(value);}//;
        
        public f32 m2A0 {get => this._m2A0(); set => this._m2A0(value);}//;
        
        public f32 m2A4 {get => this._m2A4(); set => this._m2A4(value);}//;
        
        public u8 mCurrParryOpeningType {get => this._mCurrParryOpeningType(); set => this._mCurrParryOpeningType(value);}//;
        
        public u8[] field_2A9 {get => this._field_2A9(); set => this._field_2A9(value);}//;
        
        public fopEn_enemy_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x2AC;
        }
        
        private f32 _m290() {
            return Memory.RAM.ReadF32(this.pointer + 0x290);
        }
        
        private void _m290(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x290, value);
        }
        
        private f32 _m294() {
            return Memory.RAM.ReadF32(this.pointer + 0x294);
        }
        
        private void _m294(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x294, value);
        }
        
        private f32 _m298() {
            return Memory.RAM.ReadF32(this.pointer + 0x298);
        }
        
        private void _m298(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x298, value);
        }
        
        private f32 _m29C() {
            return Memory.RAM.ReadF32(this.pointer + 0x29C);
        }
        
        private void _m29C(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x29C, value);
        }
        
        private f32 _m2A0() {
            return Memory.RAM.ReadF32(this.pointer + 0x2A0);
        }
        
        private void _m2A0(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x2A0, value);
        }
        
        private f32 _m2A4() {
            return Memory.RAM.ReadF32(this.pointer + 0x2A4);
        }
        
        private void _m2A4(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x2A4, value);
        }
        
        private u8 _mCurrParryOpeningType() {
            return Memory.RAM.ReadU8(this.pointer + 0x2A8);
        }
        
        private void _mCurrParryOpeningType(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x2A8, value);
        }
        
        // #ARRCOUNT 3
        private u8[] _field_2A9() {
            u8[] bytes = new u8[3]; for(u32 i = 0; i < 3; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x2A9 + (i * 1));} return bytes;
        }
        
        private void _field_2A9(u8[] value) {
            for(u32 i = 0; i < 3; i++){Memory.RAM.WriteU8(this.pointer + 0x2A9 + (i * 1), value[i]);}
        }
    }
}
