//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class daPy_demo_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u16 mDemoType {get => this._mDemoType(); set => this._mDemoType(value);}//;
        
        public s16 mDemoMoveAngle {get => this._mDemoMoveAngle(); set => this._mDemoMoveAngle(value);}//;
        
        public s16 mTimer {get => this._mTimer(); set => this._mTimer(value);}//;
        
        public s16 mParam2 {get => this._mParam2(); set => this._mParam2(value);}//;
        
        public u32 mParam0 {get => this._mParam0(); set => this._mParam0(value);}//;
        
        public u32 mParam1 {get => this._mParam1(); set => this._mParam1(value);}//;
        
        public u32 mDemoMode {get => this._mDemoMode(); set => this._mDemoMode(value);}//;
        
        public f32 mStick {get => this._mStick(); set => this._mStick(value);}//;
        
        public daPy_demo_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x18;
        }
        
        private u16 _mDemoType() {
            return Memory.RAM.ReadU16(this.pointer + 0x00);
        }
        
        private void _mDemoType(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x00, value);
        }
        
        private s16 _mDemoMoveAngle() {
            return Memory.RAM.ReadS16(this.pointer + 0x02);
        }
        
        private void _mDemoMoveAngle(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x02, value);
        }
        
        private s16 _mTimer() {
            return Memory.RAM.ReadS16(this.pointer + 0x04);
        }
        
        private void _mTimer(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x04, value);
        }
        
        private s16 _mParam2() {
            return Memory.RAM.ReadS16(this.pointer + 0x06);
        }
        
        private void _mParam2(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x06, value);
        }
        
        private u32 _mParam0() {
            return Memory.RAM.ReadU32(this.pointer + 0x08);
        }
        
        private void _mParam0(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x08, value);
        }
        
        private u32 _mParam1() {
            return Memory.RAM.ReadU32(this.pointer + 0x0C);
        }
        
        private void _mParam1(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x0C, value);
        }
        
        private u32 _mDemoMode() {
            return Memory.RAM.ReadU32(this.pointer + 0x10);
        }
        
        private void _mDemoMode(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x10, value);
        }
        
        private f32 _mStick() {
            return Memory.RAM.ReadF32(this.pointer + 0x14);
        }
        
        private void _mStick(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x14, value);
        }
    }
}
