//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class daPy_py_c : fopAc_ac_c
    {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u8 mCutType {get => this._mCutType(); set => this._mCutType(value);}//;
        
        public u8 mCutCount {get => this._mCutCount(); set => this._mCutCount(value);}//;
        
        public u8[] field_0x292 {get => this._field_0x292(); set => this._field_0x292(value);}//;
        
        public s16 mDamageWaitTimer {get => this._mDamageWaitTimer(); set => this._mDamageWaitTimer(value);}//;
        
        public s16 mQuakeTimer {get => this._mQuakeTimer(); set => this._mQuakeTimer(value);}//;
        
        public u32 mFace {get => this._mFace(); set => this._mFace(value);}//;
        
        public u32 mNoResetFlg0 {get => this._mNoResetFlg0(); set => this._mNoResetFlg0(value);}//;
        
        public u32 mNoResetFlg1 {get => this._mNoResetFlg1(); set => this._mNoResetFlg1(value);}//;
        
        public u32 mResetFlg0 {get => this._mResetFlg0(); set => this._mResetFlg0(value);}//;
        
        public f32 field_0x2a8 {get => this._field_0x2a8(); set => this._field_0x2a8(value);}//;
        
        public f32 mHeight {get => this._mHeight(); set => this._mHeight(value);}//;
        
        public f32 field_0x2b0 {get => this._field_0x2b0(); set => this._field_0x2b0(value);}//;
        
        public csXyz mBodyAngle {get => this._mBodyAngle(); set => this._mBodyAngle(value);}//;
        
        public u8[] field_0x2BA {get => this._field_0x2BA(); set => this._field_0x2BA(value);}//;
        
        public cXyz mHeadTopPos {get => this._mHeadTopPos(); set => this._mHeadTopPos(value);}//;
        
        public cXyz mSwordTopPos {get => this._mSwordTopPos(); set => this._mSwordTopPos(value);}//;
        
        public cXyz mLeftHandPos {get => this._mLeftHandPos(); set => this._mLeftHandPos(value);}//;
        
        public cXyz mRightHandPos {get => this._mRightHandPos(); set => this._mRightHandPos(value);}//;
        
        public cXyz mRopePos {get => this._mRopePos(); set => this._mRopePos(value);}//;
        
        public cXyz field_0x2f8 {get => this._field_0x2f8(); set => this._field_0x2f8(value);}//;
        
        public daPy_demo_c mDemo {get => this._mDemo(); set => this._mDemo(value);}//;
        
        public daPy_py_c(u32 pointer) : base(pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u8 _mCutType() {
            return Memory.RAM.ReadU8(this.pointer + 0x290);
        }
        
        private void _mCutType(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x290, value);
        }
        
        private u8 _mCutCount() {
            return Memory.RAM.ReadU8(this.pointer + 0x291);
        }
        
        private void _mCutCount(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x291, value);
        }
        
        // #ARRCOUNT 2
        private u8[] _field_0x292() {
            u8[] bytes = new u8[2]; for(u32 i = 0; i < 2; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x292 + (i * 1));} return bytes;
        }
        
        private void _field_0x292(u8[] value) {
            for(u32 i = 0; i < 2; i++){Memory.RAM.WriteU8(this.pointer + 0x292 + (i * 1), value[i]);}
        }
        
        private s16 _mDamageWaitTimer() {
            return Memory.RAM.ReadS16(this.pointer + 0x294);
        }
        
        private void _mDamageWaitTimer(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x294, value);
        }
        
        private s16 _mQuakeTimer() {
            return Memory.RAM.ReadS16(this.pointer + 0x296);
        }
        
        private void _mQuakeTimer(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x296, value);
        }
        
        private u32 _mFace() {
            return Memory.RAM.ReadU32(this.pointer + 0x298);
        }
        
        private void _mFace(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x298, value);
        }
        
        private u32 _mNoResetFlg0() {
            return Memory.RAM.ReadU32(this.pointer + 0x29C);
        }
        
        private void _mNoResetFlg0(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x29C, value);
        }
        
        private u32 _mNoResetFlg1() {
            return Memory.RAM.ReadU32(this.pointer + 0x2A0);
        }
        
        private void _mNoResetFlg1(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x2A0, value);
        }
        
        private u32 _mResetFlg0() {
            return Memory.RAM.ReadU32(this.pointer + 0x2A4);
        }
        
        private void _mResetFlg0(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x2A4, value);
        }
        
        private f32 _field_0x2a8() {
            return Memory.RAM.ReadF32(this.pointer + 0x2A8);
        }
        
        private void _field_0x2a8(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x2A8, value);
        }
        
        private f32 _mHeight() {
            return Memory.RAM.ReadF32(this.pointer + 0x2AC);
        }
        
        private void _mHeight(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x2AC, value);
        }
        
        private f32 _field_0x2b0() {
            return Memory.RAM.ReadF32(this.pointer + 0x2B0);
        }
        
        private void _field_0x2b0(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x2B0, value);
        }
        
        private csXyz _mBodyAngle() {
            return new csXyz(this.pointer + 0x2B4);
        }
        
        private void _mBodyAngle(csXyz value) {
        }
        
        // #ARRCOUNT 2
        private u8[] _field_0x2BA() {
            u8[] bytes = new u8[2]; for(u32 i = 0; i < 2; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x2BA + (i * 1));} return bytes;
        }
        
        private void _field_0x2BA(u8[] value) {
            for(u32 i = 0; i < 2; i++){Memory.RAM.WriteU8(this.pointer + 0x2BA + (i * 1), value[i]);}
        }
        
        private cXyz _mHeadTopPos() {
            return new cXyz(this.pointer + 0x2BC);
        }
        
        private void _mHeadTopPos(cXyz value) {
        }
        
        private cXyz _mSwordTopPos() {
            return new cXyz(this.pointer + 0x2C8);
        }
        
        private void _mSwordTopPos(cXyz value) {
        }
        
        private cXyz _mLeftHandPos() {
            return new cXyz(this.pointer + 0x2D4);
        }
        
        private void _mLeftHandPos(cXyz value) {
        }
        
        private cXyz _mRightHandPos() {
            return new cXyz(this.pointer + 0x2E0);
        }
        
        private void _mRightHandPos(cXyz value) {
        }
        
        private cXyz _mRopePos() {
            return new cXyz(this.pointer + 0x2EC);
        }
        
        private void _mRopePos(cXyz value) {
        }
        
        private cXyz _field_0x2f8() {
            return new cXyz(this.pointer + 0x2F8);
        }
        
        private void _field_0x2f8(cXyz value) {
        }
        
        private daPy_demo_c _mDemo() {
            return new daPy_demo_c(this.pointer + 0x304);
        }
        
        private void _mDemo(daPy_demo_c value) {
        }
    }
}
