//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class daPy_mtxFollowEcallBack_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        //public JPABaseEmitter mpEmitter {get => this._mpEmitter(); set => this._mpEmitter(value);}//;
        
        //public MtxP mpMtx {get => this._mpMtx(); set => this._mpMtx(value);}//;
        
        public daPy_mtxFollowEcallBack_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0C;
        }
/*        
        private JPABaseEmitter _mpEmitter() {
            return new JPABaseEmitter(this.pointer + 0x04);
        }
        
        private void _mpEmitter(JPABaseEmitter value) {
        }
        
        private MtxP _mpMtx() {
            return new MtxP(this.pointer + 0x08);
        }
        
        private void _mpMtx(MtxP value) {
        }*/
    }
}
