//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class WrapperVec3us {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u16 x {get => this._x(); set => this._x(value);}//;
        
        public u16 y {get => this._y(); set => this._y(value);}//;
        
        public u16 z {get => this._z(); set => this._z(value);}//;
        
        public WrapperVec3us(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x06;
        }
        
        private u16 _x() {
            return Memory.RAM.ReadU16(this.pointer + 0x00);
        }
        
        private void _x(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x00, value);
        }
        
        private u16 _y() {
            return Memory.RAM.ReadU16(this.pointer + 0x02);
        }
        
        private void _y(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x02, value);
        }
        
        private u16 _z() {
            return Memory.RAM.ReadU16(this.pointer + 0x04);
        }
        
        private void _z(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x04, value);
        }
    }
}
