//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dSv_reserve_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u8[] mReserve {get => this._mReserve(); set => this._mReserve(value);}//;
        
        public dSv_reserve_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x50;
        }
        
        // #ARRCOUNT 0x50
        private u8[] _mReserve() {
            u8[] bytes = new u8[0x50]; for(u32 i = 0; i < 0x50; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x0 + (i * 1));} return bytes;
        }
        
        private void _mReserve(u8[] value) {
            for(u32 i = 0; i < 0x50; i++){Memory.RAM.WriteU8(this.pointer + 0x0 + (i * 1), value[i]);}
        }
    }
}
