//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dSv_player_return_place_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public char[] mName {get => this._mName(); set => this._mName(value);}//;
        
        public s8 mRoomNo {get => this._mRoomNo(); set => this._mRoomNo(value);}//;
        
        public u8 mPoint {get => this._mPoint(); set => this._mPoint(value);}//;
        
        public u8 unk_0xa {get => this._unk_0xa(); set => this._unk_0xa(value);}//;
        
        public u8 unk_0xb {get => this._unk_0xb(); set => this._unk_0xb(value);}//;
        
        public dSv_player_return_place_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0xC;
        }
        
        // #ARRCOUNT 8
        private char[] _mName() {
            char[] bytes = new char[8]; for(u32 i = 0; i < 8; i++){bytes[i] = (char)Memory.RAM.ReadU8(this.pointer + 0x00 + (i * 1));} return bytes;
        }
        
        private void _mName(char[] value) {
            for(u32 i = 0; i < 8; i++){Memory.RAM.WriteU8(this.pointer + 0x00 + (i * 1), (u8)value[i]);}
        }
        
        private s8 _mRoomNo() {
            return Memory.RAM.ReadS8(this.pointer + 0x08);
        }
        
        private void _mRoomNo(s8 value) {
            Memory.RAM.WriteS8(this.pointer + 0x08, value);
        }
        
        private u8 _mPoint() {
            return Memory.RAM.ReadU8(this.pointer + 0x09);
        }
        
        private void _mPoint(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x09, value);
        }
        
        private u8 _unk_0xa() {
            return Memory.RAM.ReadU8(this.pointer + 0x0A);
        }
        
        private void _unk_0xa(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x0A, value);
        }
        
        private u8 _unk_0xb() {
            return Memory.RAM.ReadU8(this.pointer + 0x0B);
        }
        
        private void _unk_0xb(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x0B, value);
        }
    }
}
