//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dSv_player_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public dSv_player_status_a_c mPlayerStatusA {get => this._mPlayerStatusA(); set => this._mPlayerStatusA(value);}//;
        
        public dSv_player_status_b_c mPlayerStatusB {get => this._mPlayerStatusB(); set => this._mPlayerStatusB(value);}//;
        
        public dSv_player_return_place_c mReturnPlace {get => this._mReturnPlace(); set => this._mReturnPlace(value);}//;
        
        public dSv_player_item_c mPlayerItem {get => this._mPlayerItem(); set => this._mPlayerItem(value);}//;
        
        public dSv_player_get_item_c mGetItem {get => this._mGetItem(); set => this._mGetItem(value);}//;
        
        public dSv_player_item_record_c mItemRecord {get => this._mItemRecord(); set => this._mItemRecord(value);}//;
        
        public dSv_player_item_max_c mItemMax {get => this._mItemMax(); set => this._mItemMax(value);}//;
        
        public dSv_player_bag_item_c mBagItem {get => this._mBagItem(); set => this._mBagItem(value);}//;
        
        public dSv_player_get_bag_item_c mGetBagItem {get => this._mGetBagItem(); set => this._mGetBagItem(value);}//;
        
        public dSv_player_bag_item_record_c mBagItemRecord {get => this._mBagItemRecord(); set => this._mBagItemRecord(value);}//;
        
        public dSv_player_collect_c mCollect {get => this._mCollect(); set => this._mCollect(value);}//;
        
        public dSv_player_map_c mMap {get => this._mMap(); set => this._mMap(value);}//;
        
        public dSv_player_info_c mInfo {get => this._mInfo(); set => this._mInfo(value);}//;
        
        public dSv_player_config_c mConfig {get => this._mConfig(); set => this._mConfig(value);}//;
        
        public dSv_player_priest_c mPriest {get => this._mPriest(); set => this._mPriest(value);}//;
        
        public dSv_player_status_c_c[] mStatusC {get => this._mStatusC(); set => this._mStatusC(value);}//;
        
        public u32 mTbox {get => this._mTbox(); set => this._mTbox(value);}//;
        
        public u32[] mSwitch {get => this._mSwitch(); set => this._mSwitch(value);}//;
        
        public u32[] mItem {get => this._mItem(); set => this._mItem(value);}//;
        
        public u32[] mVisitedRoom {get => this._mVisitedRoom(); set => this._mVisitedRoom(value);}//;
        
        public u8 mKeyNum {get => this._mKeyNum(); set => this._mKeyNum(value);}//;
        
        public u8 mDungeonItem {get => this._mDungeonItem(); set => this._mDungeonItem(value);}//;
        
        public dSv_player_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x380;
        }
        
        private dSv_player_status_a_c _mPlayerStatusA() {
            return new dSv_player_status_a_c(this.pointer + 0x000);
        }
        
        private void _mPlayerStatusA(dSv_player_status_a_c value) {
        }
        
        private dSv_player_status_b_c _mPlayerStatusB() {
            return new dSv_player_status_b_c(this.pointer + 0x018);
        }
        
        private void _mPlayerStatusB(dSv_player_status_b_c value) {
        }
        
        private dSv_player_return_place_c _mReturnPlace() {
            return new dSv_player_return_place_c(this.pointer + 0x030);
        }
        
        private void _mReturnPlace(dSv_player_return_place_c value) {
        }
        
        private dSv_player_item_c _mPlayerItem() {
            return new dSv_player_item_c(this.pointer + 0x03C);
        }
        
        private void _mPlayerItem(dSv_player_item_c value) {
        }
        
        private dSv_player_get_item_c _mGetItem() {
            return new dSv_player_get_item_c(this.pointer + 0x051);
        }
        
        private void _mGetItem(dSv_player_get_item_c value) {
        }
        
        private dSv_player_item_record_c _mItemRecord() {
            return new dSv_player_item_record_c(this.pointer + 0x066);
        }
        
        private void _mItemRecord(dSv_player_item_record_c value) {
        }
        
        private dSv_player_item_max_c _mItemMax() {
            return new dSv_player_item_max_c(this.pointer + 0x06E);
        }
        
        private void _mItemMax(dSv_player_item_max_c value) {
        }
        
        private dSv_player_bag_item_c _mBagItem() {
            return new dSv_player_bag_item_c(this.pointer + 0x076);
        }
        
        private void _mBagItem(dSv_player_bag_item_c value) {
        }
        
        private dSv_player_get_bag_item_c _mGetBagItem() {
            return new dSv_player_get_bag_item_c(this.pointer + 0x090);
        }
        
        private void _mGetBagItem(dSv_player_get_bag_item_c value) {
        }
        
        private dSv_player_bag_item_record_c _mBagItemRecord() {
            return new dSv_player_bag_item_record_c(this.pointer + 0x09C);
        }
        
        private void _mBagItemRecord(dSv_player_bag_item_record_c value) {
        }
        
        private dSv_player_collect_c _mCollect() {
            return new dSv_player_collect_c(this.pointer + 0x0B4);
        }
        
        private void _mCollect(dSv_player_collect_c value) {
        }
        
        private dSv_player_map_c _mMap() {
            return new dSv_player_map_c(this.pointer + 0x0C4);
        }
        
        private void _mMap(dSv_player_map_c value) {
        }
        
        private dSv_player_info_c _mInfo() {
            return new dSv_player_info_c(this.pointer + 0x148);
        }
        
        private void _mInfo(dSv_player_info_c value) {
        }
        
        private dSv_player_config_c _mConfig() {
            return new dSv_player_config_c(this.pointer + 0x1A4);
        }
        
        private void _mConfig(dSv_player_config_c value) {
        }
        
        private dSv_player_priest_c _mPriest() {
            return new dSv_player_priest_c(this.pointer + 0x1AC);
        }
        
        private void _mPriest(dSv_player_priest_c value) {
        }
        
        // #ARRCOUNT 4
        private dSv_player_status_c_c[] _mStatusC() {
          dSv_player_status_c_c[] substructs = new dSv_player_status_c_c[4]; for(u32 i = 0; i < 4; i++){substructs[i] = new dSv_player_status_c_c(this.pointer + 0x1BC + (i * dSv_player_status_c_c.getSize()));}; return substructs;
        }
        
        private void _mStatusC(dSv_player_status_c_c[] value) {
        }
        
        private u32 _mTbox() {
            return Memory.RAM.ReadU32(this.pointer + 0x00);
        }
        
        private void _mTbox(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x00, value);
        }
        
        // #ARRCOUNT 4
        private u32[] _mSwitch() {
            u32[] bytes = new u32[4]; for(u32 i = 0; i < 4; i++){bytes[i] = Memory.RAM.ReadU32(this.pointer + 0x04 + (i * 4));} return bytes;
        }
        
        private void _mSwitch(u32[] value) {
            for(u32 i = 0; i < 4; i++){Memory.RAM.WriteU32(this.pointer + 0x04 + (i * 4), value[i]);}
        }
        
        // #ARRCOUNT 1
        private u32[] _mItem() {
            u32[] bytes = new u32[1]; for(u32 i = 0; i < 1; i++){bytes[i] = Memory.RAM.ReadU32(this.pointer + 0x14 + (i * 4));} return bytes;
        }
        
        private void _mItem(u32[] value) {
            for(u32 i = 0; i < 1; i++){Memory.RAM.WriteU32(this.pointer + 0x14 + (i * 4), value[i]);}
        }
        
        // #ARRCOUNT 2
        private u32[] _mVisitedRoom() {
            u32[] bytes = new u32[2]; for(u32 i = 0; i < 2; i++){bytes[i] = Memory.RAM.ReadU32(this.pointer + 0x18 + (i * 4));} return bytes;
        }
        
        private void _mVisitedRoom(u32[] value) {
            for(u32 i = 0; i < 2; i++){Memory.RAM.WriteU32(this.pointer + 0x18 + (i * 4), value[i]);}
        }
        
        private u8 _mKeyNum() {
            return Memory.RAM.ReadU8(this.pointer + 0x20);
        }
        
        private void _mKeyNum(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x20, value);
        }
        
        private u8 _mDungeonItem() {
            return Memory.RAM.ReadU8(this.pointer + 0x21);
        }
        
        private void _mDungeonItem(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x21, value);
        }
    }
}
