//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dSv_player_item_record2_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u8 mPictureNum {get => this._mPictureNum(); set => this._mPictureNum(value);}//;
        
        public u8 mArrowNum {get => this._mArrowNum(); set => this._mArrowNum(value);}//;
        
        public u8 mBombNum {get => this._mBombNum(); set => this._mBombNum(value);}//;
        
        public dSv_player_item_record2_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x3;
        }
        
        private u8 _mPictureNum() {
            return Memory.RAM.ReadU8(this.pointer + 0x0);
        }
        
        private void _mPictureNum(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x0, value);
        }
        
        private u8 _mArrowNum() {
            return Memory.RAM.ReadU8(this.pointer + 0x1);
        }
        
        private void _mArrowNum(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1, value);
        }
        
        private u8 _mBombNum() {
            return Memory.RAM.ReadU8(this.pointer + 0x2);
        }
        
        private void _mBombNum(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x2, value);
        }
    }
}
