//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dSv_zoneActor_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32[] mActorFlags {get => this._mActorFlags(); set => this._mActorFlags(value);}//;
        
        public dSv_zoneActor_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x40;
        }
        
        // #ARRCOUNT 16
        private u32[] _mActorFlags() {
            u32[] bytes = new u32[16]; for(u32 i = 0; i < 16; i++){bytes[i] = Memory.RAM.ReadU32(this.pointer + 0x0 + (i * 4));} return bytes;
        }
        
        private void _mActorFlags(u32[] value) {
            for(u32 i = 0; i < 16; i++){Memory.RAM.WriteU32(this.pointer + 0x0 + (i * 4), value[i]);}
        }
    }
}
