//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dSv_player_status_c_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public dSv_player_status_a_c mRecollectStatusA {get => this._mRecollectStatusA(); set => this._mRecollectStatusA(value);}//;
        
        public dSv_player_item_c mRecollectItem {get => this._mRecollectItem(); set => this._mRecollectItem(value);}//;
        
        public dSv_player_item_record2_c mRecollectItemRecord {get => this._mRecollectItemRecord(); set => this._mRecollectItemRecord(value);}//;
        
        public dSv_player_item_max2_c mRecollectItemMax {get => this._mRecollectItemMax(); set => this._mRecollectItemMax(value);}//;
        
        public dSv_player_bag_item_c mRecollectBagItem {get => this._mRecollectBagItem(); set => this._mRecollectBagItem(value);}//;
        
        public dSv_player_bag_item_record_c mRecollectBagItemRecord {get => this._mRecollectBagItemRecord(); set => this._mRecollectBagItemRecord(value);}//;
        
        public dSv_player_collect_c mRecollectCollect {get => this._mRecollectCollect(); set => this._mRecollectCollect(value);}//;
        
        public dSv_player_status_c_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x70;
        }
        
        private dSv_player_status_a_c _mRecollectStatusA() {
            return new dSv_player_status_a_c(this.pointer + 0x00);
        }
        
        private void _mRecollectStatusA(dSv_player_status_a_c value) {
        }
        
        private dSv_player_item_c _mRecollectItem() {
            return new dSv_player_item_c(this.pointer + 0x18);
        }
        
        private void _mRecollectItem(dSv_player_item_c value) {
        }
        
        private dSv_player_item_record2_c _mRecollectItemRecord() {
            return new dSv_player_item_record2_c(this.pointer + 0x2D);
        }
        
        private void _mRecollectItemRecord(dSv_player_item_record2_c value) {
        }
        
        private dSv_player_item_max2_c _mRecollectItemMax() {
            return new dSv_player_item_max2_c(this.pointer + 0x30);
        }
        
        private void _mRecollectItemMax(dSv_player_item_max2_c value) {
        }
        
        private dSv_player_bag_item_c _mRecollectBagItem() {
            return new dSv_player_bag_item_c(this.pointer + 0x33);
        }
        
        private void _mRecollectBagItem(dSv_player_bag_item_c value) {
        }
        
        private dSv_player_bag_item_record_c _mRecollectBagItemRecord() {
            return new dSv_player_bag_item_record_c(this.pointer + 0x4B);
        }
        
        private void _mRecollectBagItemRecord(dSv_player_bag_item_record_c value) {
        }
        
        private dSv_player_collect_c _mRecollectCollect() {
            return new dSv_player_collect_c(this.pointer + 0x63);
        }
        
        private void _mRecollectCollect(dSv_player_collect_c value) {
        }
    }
}
