//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dStage_FileList_dt_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 mParam {get => this._mParam(); set => this._mParam(value);}//;
        
        public f32 mSeaLevel {get => this._mSeaLevel(); set => this._mSeaLevel(value);}//;
        
        public dStage_FileList_dt_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u32 _mParam() {
            return Memory.RAM.ReadU32(this.pointer + 0x0);
        }
        
        private void _mParam(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x0, value);
        }
        
        private f32 _mSeaLevel() {
            return Memory.RAM.ReadF32(this.pointer + 0x4);
        }
        
        private void _mSeaLevel(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x4, value);
        }
    }
}
