//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dStage_MemoryConfig_data {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u8 m_roomNo {get => this._m_roomNo(); set => this._m_roomNo(value);}//;
        
        public u8 m_blockID {get => this._m_blockID(); set => this._m_blockID(value);}//;
        
        public dStage_MemoryConfig_data(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x2;
        }
        
        private u8 _m_roomNo() {
            return Memory.RAM.ReadU8(this.pointer + 0x0);
        }
        
        private void _m_roomNo(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x0, value);
        }
        
        private u8 _m_blockID() {
            return Memory.RAM.ReadU8(this.pointer + 0x1);
        }
        
        private void _m_blockID(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1, value);
        }
    }
}
