//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dStage_MemoryMap_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 num {get => this._num(); set => this._num(value);}//;
        
        public u32 m_entries {get => this._m_entries(); set => this._m_entries(value);}//;
        
        public dStage_MemoryMap_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u32 _num() {
            return Memory.RAM.ReadU32(this.pointer + 0x0);
        }
        
        private void _num(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x0, value);
        }
        
        private u32 _m_entries() {
            return Memory.RAM.ReadU32(this.pointer + 0x4);
        }
        
        private void _m_entries(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x4, value);
        }
    }
}
