//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dStage_nextStage_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public s8 mEnable {get => this._mEnable(); set => this._mEnable(value);}//;
        
        public s8 mWipe {get => this._mWipe(); set => this._mWipe(value);}//;
        
        public dStage_nextStage_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0xE;
        }
        
        private s8 _mEnable() {
            return Memory.RAM.ReadS8(this.pointer + 0xC);
        }
        
        private void _mEnable(s8 value) {
            Memory.RAM.WriteS8(this.pointer + 0xC, value);
        }
        
        private s8 _mWipe() {
            return Memory.RAM.ReadS8(this.pointer + 0xD);
        }
        
        private void _mWipe(s8 value) {
            Memory.RAM.WriteS8(this.pointer + 0xD, value);
        }
    }
}
