//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dStage_dPnt_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u8 field_0x0 {get => this._field_0x0(); set => this._field_0x0(value);}//;
        
        public u8 field_0x1 {get => this._field_0x1(); set => this._field_0x1(value);}//;
        
        public u8 field_0x2 {get => this._field_0x2(); set => this._field_0x2(value);}//;
        
        public u8 field_0x3 {get => this._field_0x3(); set => this._field_0x3(value);}//;
        
        public cXyz m_position {get => this._m_position(); set => this._m_position(value);}//;
        
        public dStage_dPnt_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x10;
        }
        
        private u8 _field_0x0() {
            return Memory.RAM.ReadU8(this.pointer + 0x0);
        }
        
        private void _field_0x0(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x0, value);
        }
        
        private u8 _field_0x1() {
            return Memory.RAM.ReadU8(this.pointer + 0x1);
        }
        
        private void _field_0x1(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1, value);
        }
        
        private u8 _field_0x2() {
            return Memory.RAM.ReadU8(this.pointer + 0x2);
        }
        
        private void _field_0x2(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x2, value);
        }
        
        private u8 _field_0x3() {
            return Memory.RAM.ReadU8(this.pointer + 0x3);
        }
        
        private void _field_0x3(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x3, value);
        }
        
        private cXyz _m_position() {
            return new cXyz(this.pointer + 0x4);
        }
        
        private void _m_position(cXyz value) {
        }
    }
}
