//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dStage_EventInfo_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public s32 num {get => this._num(); set => this._num(value);}//;
        
        public dStage_Event_dt_c events {get => this._events(); set => this._events(value);}//;
        
        public dStage_EventInfo_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x08;
        }
        
        private s32 _num() {
            return Memory.RAM.ReadS32(this.pointer + 0x00);
        }
        
        private void _num(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x00, value);
        }
        
        private dStage_Event_dt_c _events() {
            return new dStage_Event_dt_c(this.pointer + 0x04);
        }
        
        private void _events(dStage_Event_dt_c value) {
        }
    }
}
