//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dStage_objectNameInf {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public char[] mName {get => this._mName(); set => this._mName(value);}//;
        
        public s16 mProcName {get => this._mProcName(); set => this._mProcName(value);}//;
        
        public s8 mSubtype {get => this._mSubtype(); set => this._mSubtype(value);}//;
        
        public s8 mGbaName {get => this._mGbaName(); set => this._mGbaName(value);}//;
        
        public dStage_objectNameInf(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0xC;
        }
        
        // #ARRCOUNT 8
        private char[] _mName() {
            char[] bytes = new char[8]; for(u32 i = 0; i < 8; i++){bytes[i] = (char)Memory.RAM.ReadU8(this.pointer + 0x0 + (i * 1));} return bytes; // DEADBEEF TODO: Fix Addr
        }
        
        private void _mName(char[] value) {
            for(u32 i = 0; i < 8; i++){Memory.RAM.WriteU8(this.pointer + 0x0 + (i * 1), (u8)value[i]);} // DEADBEEF TODO: Fix Addr
        }
        
        private s16 _mProcName() {
            return Memory.RAM.ReadS16(this.pointer + 0x0); // DEADBEEF TODO: Fix Addr
        }
        
        private void _mProcName(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x0, value);// DEADBEEF TODO: Fix Addr
        }
        
        private s8 _mSubtype() {
            return Memory.RAM.ReadS8(this.pointer + 0x0); // DEADBEEF TODO: Fix Addr
        }
        
        private void _mSubtype(s8 value) {
            Memory.RAM.WriteS8(this.pointer + 0x0, value);// DEADBEEF TODO: Fix Addr
        }
        
        private s8 _mGbaName() {
            return Memory.RAM.ReadS8(this.pointer + 0x0); // DEADBEEF TODO: Fix Addr
        }
        
        private void _mGbaName(s8 value) {
            Memory.RAM.WriteS8(this.pointer + 0x0, value);// DEADBEEF TODO: Fix Addr
        }
    }
}
