//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dStage_Ship_data {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public cXyz m_pos {get => this._m_pos(); set => this._m_pos(value);}//;
        
        public s16 m_angle {get => this._m_angle(); set => this._m_angle(value);}//;
        
        public u8 field_0xe {get => this._field_0xe(); set => this._field_0xe(value);}//;
        
        public u8 field_0xf {get => this._field_0xf(); set => this._field_0xf(value);}//;
        
        public dStage_Ship_data(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private cXyz _m_pos() {
            return new cXyz(this.pointer + 0x0);
        }
        
        private void _m_pos(cXyz value) {
        }
        
        private s16 _m_angle() {
            return Memory.RAM.ReadS16(this.pointer + 0xC);
        }
        
        private void _m_angle(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0xC, value);
        }
        
        private u8 _field_0xe() {
            return Memory.RAM.ReadU8(this.pointer + 0xE);
        }
        
        private void _field_0xe(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0xE, value);
        }
        
        private u8 _field_0xf() {
            return Memory.RAM.ReadU8(this.pointer + 0xF);
        }
        
        private void _field_0xf(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0xF, value);
        }
    }
}
