//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dStage_fileHeader {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 chunkCount {get => this._chunkCount(); set => this._chunkCount(value);}//;
        
        public dStage_fileHeader(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u32 _chunkCount() {
            return Memory.RAM.ReadU32(this.pointer + 0x0);
        }
        
        private void _chunkCount(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x0, value);
        }
    }
}
