//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dStage_Lbnk_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 m_num {get => this._m_num(); set => this._m_num(value);}//;
        
        public u8 m_bank {get => this._m_bank(); set => this._m_bank(value);}//;
        
        public dStage_Lbnk_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u32 _m_num() {
            return Memory.RAM.ReadU32(this.pointer + 0x00);
        }
        
        private void _m_num(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x00, value);
        }
        
        private u8 _m_bank() {
            return Memory.RAM.ReadU8(this.pointer + 0x04);
        }
        
        private void _m_bank(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x04, value);
        }
    }
}
