//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dStage_nodeHeader {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 m_tag {get => this._m_tag(); set => this._m_tag(value);}//;
        
        public u32 m_entryNum {get => this._m_entryNum(); set => this._m_entryNum(value);}//;
        
        public u32 m_offset {get => this._m_offset(); set => this._m_offset(value);}//;
        
        public dStage_nodeHeader(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u32 _m_tag() {
            return Memory.RAM.ReadU32(this.pointer + 0x0);
        }
        
        private void _m_tag(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x0, value);
        }
        
        private u32 _m_entryNum() {
            return Memory.RAM.ReadU32(this.pointer + 0x4);
        }
        
        private void _m_entryNum(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x4, value);
        }
        
        private u32 _m_offset() {
            return Memory.RAM.ReadU32(this.pointer + 0x8);
        }
        
        private void _m_offset(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x8, value);
        }
    }
}
