//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dStage_startStage_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public char[] mName {get => this._mName(); set => this._mName(value);}//;
        
        public s16 mPoint {get => this._mPoint(); set => this._mPoint(value);}//;
        
        public s8 mRoomNo {get => this._mRoomNo(); set => this._mRoomNo(value);}//;
        
        public s8 mLayer {get => this._mLayer(); set => this._mLayer(value);}//;
        
        public dStage_startStage_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        // #ARRCOUNT 8
        private char[] _mName() {
            char[] bytes = new char[8]; for(u32 i = 0; i < 8; i++){bytes[i] = (char)Memory.RAM.ReadU8(this.pointer + 0x0 + (i * 1));} return bytes;
        }
        
        private void _mName(char[] value) {
            for(u32 i = 0; i < 8; i++){Memory.RAM.WriteU8(this.pointer + 0x0 + (i * 1), (u8)value[i]);}
        }
        
        private s16 _mPoint() {
            return Memory.RAM.ReadS16(this.pointer + 0x8);
        }
        
        private void _mPoint(s16 value) {
            Memory.RAM.WriteS16(this.pointer + 0x8, value);
        }
        
        private s8 _mRoomNo() {
            return Memory.RAM.ReadS8(this.pointer + 0xA);
        }
        
        private void _mRoomNo(s8 value) {
            Memory.RAM.WriteS8(this.pointer + 0xA, value);
        }
        
        private s8 _mLayer() {
            return Memory.RAM.ReadS8(this.pointer + 0xB);
        }
        
        private void _mLayer(s8 value) {
            Memory.RAM.WriteS8(this.pointer + 0xB, value);
        }
    }
}
