//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class FuncTable {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public char[] identifier {get => this._identifier(); set => this._identifier(value);}//;
        
        //public dStage_Func function {get => this._function(); set => this._function(value);}//;
        
        public FuncTable(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        // #ARRCOUNT 5
        private char[] _identifier() {
            char[] bytes = new char[5]; for(u32 i = 0; i < 5; i++){bytes[i] = (char)Memory.RAM.ReadU8(this.pointer + 0x0 + (i * 1));} return bytes;
        }
        
        private void _identifier(char[] value) {
            for(u32 i = 0; i < 5; i++){Memory.RAM.WriteU8(this.pointer + 0x0 + (i * 1), (u8)value[i]);}
        }
/*        
        private dStage_Func _function() {
            return new dStage_Func(this.pointer + 0x0); // DEADBEEF TODO: Fix Addr
        }
        
        private void _function(dStage_Func value) {
        }*/
    }
}
