//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class roomRead_data_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u8 mRoomCount {get => this._mRoomCount(); set => this._mRoomCount(value);}//;
        
        public u8 field_0x1 {get => this._field_0x1(); set => this._field_0x1(value);}//;
        
        public u8 field_0x2 {get => this._field_0x2(); set => this._field_0x2(value);}//;
        
        public u8 mpRooms {get => this._mpRooms(); set => this._mpRooms(value);}//;
        
        public roomRead_data_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u8 _mRoomCount() {
            return Memory.RAM.ReadU8(this.pointer + 0x0);
        }
        
        private void _mRoomCount(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x0, value);
        }
        
        private u8 _field_0x1() {
            return Memory.RAM.ReadU8(this.pointer + 0x1);
        }
        
        private void _field_0x1(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1, value);
        }
        
        private u8 _field_0x2() {
            return Memory.RAM.ReadU8(this.pointer + 0x2);
        }
        
        private void _field_0x2(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x2, value);
        }
        
        private u8 _mpRooms() {
            return Memory.RAM.ReadU8(this.pointer + 0x4);
        }
        
        private void _mpRooms(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x4, value);
        }
    }
}
