//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class stage_palet_info_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        /*public color_RGB_class mActor_C0 {get => this._mActor_C0(); set => this._mActor_C0(value);}//;
        
        public color_RGB_class mActor_K0 {get => this._mActor_K0(); set => this._mActor_K0(value);}//;
        
        public color_RGB_class mBG0_C0 {get => this._mBG0_C0(); set => this._mBG0_C0(value);}//;
        
        public color_RGB_class mBG0_K0 {get => this._mBG0_K0(); set => this._mBG0_K0(value);}//;
        
        public color_RGB_class mBG1_C0 {get => this._mBG1_C0(); set => this._mBG1_C0(value);}//;
        
        public color_RGB_class mBG1_K0 {get => this._mBG1_K0(); set => this._mBG1_K0(value);}//;
        
        public color_RGB_class mBG2_C0 {get => this._mBG2_C0(); set => this._mBG2_C0(value);}//;
        
        public color_RGB_class mBG2_K0 {get => this._mBG2_K0(); set => this._mBG2_K0(value);}//;
        
        public color_RGB_class mBG3_C0 {get => this._mBG3_C0(); set => this._mBG3_C0(value);}//;
        
        public color_RGB_class mBG3_K0 {get => this._mBG3_K0(); set => this._mBG3_K0(value);}//;
        
        public color_RGB_class mFog {get => this._mFog(); set => this._mFog(value);}//;
        */
        public u8 mVirtIdx {get => this._mVirtIdx(); set => this._mVirtIdx(value);}//;
        
        public f32 mFogStartZ {get => this._mFogStartZ(); set => this._mFogStartZ(value);}//;
        
        public f32 mFogEndZ {get => this._mFogEndZ(); set => this._mFogEndZ(value);}//;
        
        public stage_palet_info_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        /*private color_RGB_class _mActor_C0() {
            return new color_RGB_class(this.pointer + 0x00);
        }
        
        private void _mActor_C0(color_RGB_class value) {
        }
        
        private color_RGB_class _mActor_K0() {
            return new color_RGB_class(this.pointer + 0x03);
        }
        
        private void _mActor_K0(color_RGB_class value) {
        }
        
        private color_RGB_class _mBG0_C0() {
            return new color_RGB_class(this.pointer + 0x06);
        }
        
        private void _mBG0_C0(color_RGB_class value) {
        }
        
        private color_RGB_class _mBG0_K0() {
            return new color_RGB_class(this.pointer + 0x09);
        }
        
        private void _mBG0_K0(color_RGB_class value) {
        }
        
        private color_RGB_class _mBG1_C0() {
            return new color_RGB_class(this.pointer + 0x0C);
        }
        
        private void _mBG1_C0(color_RGB_class value) {
        }
        
        private color_RGB_class _mBG1_K0() {
            return new color_RGB_class(this.pointer + 0x0F);
        }
        
        private void _mBG1_K0(color_RGB_class value) {
        }
        
        private color_RGB_class _mBG2_C0() {
            return new color_RGB_class(this.pointer + 0x12);
        }
        
        private void _mBG2_C0(color_RGB_class value) {
        }
        
        private color_RGB_class _mBG2_K0() {
            return new color_RGB_class(this.pointer + 0x15);
        }
        
        private void _mBG2_K0(color_RGB_class value) {
        }
        
        private color_RGB_class _mBG3_C0() {
            return new color_RGB_class(this.pointer + 0x18);
        }
        
        private void _mBG3_C0(color_RGB_class value) {
        }
        
        private color_RGB_class _mBG3_K0() {
            return new color_RGB_class(this.pointer + 0x1B);
        }
        
        private void _mBG3_K0(color_RGB_class value) {
        }
        
        private color_RGB_class _mFog() {
            return new color_RGB_class(this.pointer + 0x1E);
        }
        
        private void _mFog(color_RGB_class value) {
        }*/
        
        private u8 _mVirtIdx() {
            return Memory.RAM.ReadU8(this.pointer + 0x21);
        }
        
        private void _mVirtIdx(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x21, value);
        }
        
        private f32 _mFogStartZ() {
            return Memory.RAM.ReadF32(this.pointer + 0x24);
        }
        
        private void _mFogStartZ(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x24, value);
        }
        
        private f32 _mFogEndZ() {
            return Memory.RAM.ReadF32(this.pointer + 0x28);
        }
        
        private void _mFogEndZ(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x28, value);
        }
    }
}
