//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class stage_stag_info_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public f32 field_0x0 {get => this._field_0x0(); set => this._field_0x0(value);}//;
        
        public f32 field_0x4 {get => this._field_0x4(); set => this._field_0x4(value);}//;
        
        public u8 mCameraType {get => this._mCameraType(); set => this._mCameraType(value);}//;
        
        public u8 field_0x09 {get => this._field_0x09(); set => this._field_0x09(value);}//;
        
        public u16 field_0x0a {get => this._field_0x0a(); set => this._field_0x0a(value);}//;
        
        public u32 field_0x0c {get => this._field_0x0c(); set => this._field_0x0c(value);}//;
        
        public u32 field_0x10 {get => this._field_0x10(); set => this._field_0x10(value);}//;
        
        public u32 field_0x14 {get => this._field_0x14(); set => this._field_0x14(value);}//;
        
        public u32 field_0x18 {get => this._field_0x18(); set => this._field_0x18(value);}//;
        
        public u32 field_0x1c {get => this._field_0x1c(); set => this._field_0x1c(value);}//;
        
        public stage_stag_info_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private f32 _field_0x0() {
            return Memory.RAM.ReadF32(this.pointer + 0x00);
        }
        
        private void _field_0x0(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x00, value);
        }
        
        private f32 _field_0x4() {
            return Memory.RAM.ReadF32(this.pointer + 0x04);
        }
        
        private void _field_0x4(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x04, value);
        }
        
        private u8 _mCameraType() {
            return Memory.RAM.ReadU8(this.pointer + 0x08);
        }
        
        private void _mCameraType(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x08, value);
        }
        
        private u8 _field_0x09() {
            return Memory.RAM.ReadU8(this.pointer + 0x09);
        }
        
        private void _field_0x09(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x09, value);
        }
        
        private u16 _field_0x0a() {
            return Memory.RAM.ReadU16(this.pointer + 0x0A);
        }
        
        private void _field_0x0a(u16 value) {
            Memory.RAM.WriteU16(this.pointer + 0x0A, value);
        }
        
        private u32 _field_0x0c() {
            return Memory.RAM.ReadU32(this.pointer + 0x0C);
        }
        
        private void _field_0x0c(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x0C, value);
        }
        
        private u32 _field_0x10() {
            return Memory.RAM.ReadU32(this.pointer + 0x10);
        }
        
        private void _field_0x10(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x10, value);
        }
        
        private u32 _field_0x14() {
            return Memory.RAM.ReadU32(this.pointer + 0x14);
        }
        
        private void _field_0x14(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x14, value);
        }
        
        private u32 _field_0x18() {
            return Memory.RAM.ReadU32(this.pointer + 0x18);
        }
        
        private void _field_0x18(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x18, value);
        }
        
        private u32 _field_0x1c() {
            return Memory.RAM.ReadU32(this.pointer + 0x1C);
        }
        
        private void _field_0x1c(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x1C, value);
        }
    }
}
