//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class stage_vrbox_info_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 field_0x00 {get => this._field_0x00(); set => this._field_0x00(value);}//;
        
        public u32 field_0x04 {get => this._field_0x04(); set => this._field_0x04(value);}//;
        
        public u32 field_0x08 {get => this._field_0x08(); set => this._field_0x08(value);}//;
        
        public u32 field_0x0c {get => this._field_0x0c(); set => this._field_0x0c(value);}//;
        
        /*public GXColor mKumoColor {get => this._mKumoColor(); set => this._mKumoColor(value);}//;
        
        public GXColor mKumoCenterColor {get => this._mKumoCenterColor(); set => this._mKumoCenterColor(value);}//;
        
        public color_RGB_class mSkyColor {get => this._mSkyColor(); set => this._mSkyColor(value);}//;
        
        public color_RGB_class mUsoUmiColor {get => this._mUsoUmiColor(); set => this._mUsoUmiColor(value);}//;
        
        public color_RGB_class mKasumiMaeColor {get => this._mKasumiMaeColor(); set => this._mKasumiMaeColor(value);}//;*/
        
        public stage_vrbox_info_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private u32 _field_0x00() {
            return Memory.RAM.ReadU32(this.pointer + 0x00);
        }
        
        private void _field_0x00(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x00, value);
        }
        
        private u32 _field_0x04() {
            return Memory.RAM.ReadU32(this.pointer + 0x04);
        }
        
        private void _field_0x04(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x04, value);
        }
        
        private u32 _field_0x08() {
            return Memory.RAM.ReadU32(this.pointer + 0x08);
        }
        
        private void _field_0x08(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x08, value);
        }
        
        private u32 _field_0x0c() {
            return Memory.RAM.ReadU32(this.pointer + 0x0C);
        }
        
        private void _field_0x0c(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x0C, value);
        }
        
        /*private GXColor _mKumoColor() {
            return new GXColor(this.pointer + 0x10);
        }
        
        private void _mKumoColor(GXColor value) {
        }
        
        private GXColor _mKumoCenterColor() {
            return new GXColor(this.pointer + 0x14);
        }
        
        private void _mKumoCenterColor(GXColor value) {
        }
        
        private color_RGB_class _mSkyColor() {
            return new color_RGB_class(this.pointer + 0x18);
        }
        
        private void _mSkyColor(color_RGB_class value) {
        }
        
        private color_RGB_class _mUsoUmiColor() {
            return new color_RGB_class(this.pointer + 0x1B);
        }
        
        private void _mUsoUmiColor(color_RGB_class value) {
        }
        
        private color_RGB_class _mKasumiMaeColor() {
            return new color_RGB_class(this.pointer + 0x1E);
        }
        
        private void _mKasumiMaeColor(color_RGB_class value) {
        }*/
    }
}
