//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class stage_arrow_data_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public cXyz mPosition {get => this._mPosition(); set => this._mPosition(value);}//;
        
        public csXyz mAngle {get => this._mAngle(); set => this._mAngle(value);}//;
        
        public stage_arrow_data_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x14;
        }
        
        private cXyz _mPosition() {
            return new cXyz(this.pointer + 0x00);
        }
        
        private void _mPosition(cXyz value) {
        }
        
        private csXyz _mAngle() {
            return new csXyz(this.pointer + 0x0C);
        }
        
        private void _mAngle(csXyz value) {
        }
    }
}
