//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class stage_plight_info_class {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        //public Vec mPos {get => this._mPos(); set => this._mPos(value);}//;
        
        public f32 mRadius {get => this._mRadius(); set => this._mRadius(value);}//;
        
        public f32 field_0x10 {get => this._field_0x10(); set => this._field_0x10(value);}//;
        
        public f32 field_0x14 {get => this._field_0x14(); set => this._field_0x14(value);}//;
        
        public u8 mColorR {get => this._mColorR(); set => this._mColorR(value);}//;
        
        public u8 mColorG {get => this._mColorG(); set => this._mColorG(value);}//;
        
        public u8 mColorB {get => this._mColorB(); set => this._mColorB(value);}//;
        
        public u8 mFluctuation {get => this._mFluctuation(); set => this._mFluctuation(value);}//;
        
        public stage_plight_info_class(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        /*private Vec _mPos() {
            return new Vec(this.pointer + 0x00);
        }
        
        private void _mPos(Vec value) {
        }*/
        
        private f32 _mRadius() {
            return Memory.RAM.ReadF32(this.pointer + 0x0C);
        }
        
        private void _mRadius(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x0C, value);
        }
        
        private f32 _field_0x10() {
            return Memory.RAM.ReadF32(this.pointer + 0x10);
        }
        
        private void _field_0x10(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x10, value);
        }
        
        private f32 _field_0x14() {
            return Memory.RAM.ReadF32(this.pointer + 0x14);
        }
        
        private void _field_0x14(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x14, value);
        }
        
        private u8 _mColorR() {
            return Memory.RAM.ReadU8(this.pointer + 0x18);
        }
        
        private void _mColorR(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x18, value);
        }
        
        private u8 _mColorG() {
            return Memory.RAM.ReadU8(this.pointer + 0x19);
        }
        
        private void _mColorG(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x19, value);
        }
        
        private u8 _mColorB() {
            return Memory.RAM.ReadU8(this.pointer + 0x1A);
        }
        
        private void _mColorB(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1A, value);
        }
        
        private u8 _mFluctuation() {
            return Memory.RAM.ReadU8(this.pointer + 0x1B);
        }
        
        private void _mFluctuation(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1B, value);
        }
    }
}
