//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dADM_CharTbl {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public s32 mIndex_ARG {get => this._mIndex_ARG(); set => this._mIndex_ARG(value);}//;
        
        public s32 mIndex_N_ITEM0 {get => this._mIndex_N_ITEM0(); set => this._mIndex_N_ITEM0(value);}//;
        
        public s32 mIndex_N_ITEM1 {get => this._mIndex_N_ITEM1(); set => this._mIndex_N_ITEM1(value);}//;
        
        public s32 mIndex_N_ITEM2 {get => this._mIndex_N_ITEM2(); set => this._mIndex_N_ITEM2(value);}//;
        
        public s32 mIndex_N_ITEM3 {get => this._mIndex_N_ITEM3(); set => this._mIndex_N_ITEM3(value);}//;
        
        public s32 mIndex_N_ITEM4 {get => this._mIndex_N_ITEM4(); set => this._mIndex_N_ITEM4(value);}//;
        
        public s32 mIndex_N_ITEM5 {get => this._mIndex_N_ITEM5(); set => this._mIndex_N_ITEM5(value);}//;
        
        public s32 mIndex_N_ITEM6 {get => this._mIndex_N_ITEM6(); set => this._mIndex_N_ITEM6(value);}//;
        
        public s32 mIndex_N_ITEM7 {get => this._mIndex_N_ITEM7(); set => this._mIndex_N_ITEM7(value);}//;
        
        public s32 mIndex_N_ITEM8 {get => this._mIndex_N_ITEM8(); set => this._mIndex_N_ITEM8(value);}//;
        
        public s32 mIndex_N_ITEM9 {get => this._mIndex_N_ITEM9(); set => this._mIndex_N_ITEM9(value);}//;
        
        public s32 mIndex_N_ITEM10 {get => this._mIndex_N_ITEM10(); set => this._mIndex_N_ITEM10(value);}//;
        
        public s32 mIndex_N_ITEM11 {get => this._mIndex_N_ITEM11(); set => this._mIndex_N_ITEM11(value);}//;
        
        public s32 mIndex_N_ITEM12 {get => this._mIndex_N_ITEM12(); set => this._mIndex_N_ITEM12(value);}//;
        
        public s32 mIndex_N_ITEM13 {get => this._mIndex_N_ITEM13(); set => this._mIndex_N_ITEM13(value);}//;
        
        public s32 mIndex_N_ITEM14 {get => this._mIndex_N_ITEM14(); set => this._mIndex_N_ITEM14(value);}//;
        
        public s32 mIndex_N_ITEM15 {get => this._mIndex_N_ITEM15(); set => this._mIndex_N_ITEM15(value);}//;
        
        public s32 mIndex_percent {get => this._mIndex_percent(); set => this._mIndex_percent(value);}//;
        
        public s32 mIndex_ITEM0 {get => this._mIndex_ITEM0(); set => this._mIndex_ITEM0(value);}//;
        
        public s32 mIndex_ITEM1 {get => this._mIndex_ITEM1(); set => this._mIndex_ITEM1(value);}//;
        
        public s32 mIndex_ITEM2 {get => this._mIndex_ITEM2(); set => this._mIndex_ITEM2(value);}//;
        
        public s32 mIndex_ITEM3 {get => this._mIndex_ITEM3(); set => this._mIndex_ITEM3(value);}//;
        
        public s32 mIndex_ITEM4 {get => this._mIndex_ITEM4(); set => this._mIndex_ITEM4(value);}//;
        
        public s32 mIndex_ITEM5 {get => this._mIndex_ITEM5(); set => this._mIndex_ITEM5(value);}//;
        
        public s32 mIndex_ITEM6 {get => this._mIndex_ITEM6(); set => this._mIndex_ITEM6(value);}//;
        
        public s32 mIndex_ITEM7 {get => this._mIndex_ITEM7(); set => this._mIndex_ITEM7(value);}//;
        
        public dADM_CharTbl(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private s32 _mIndex_ARG() {
            return Memory.RAM.ReadS32(this.pointer + 0x28);
        }
        
        private void _mIndex_ARG(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x28, value);
        }
        
        private s32 _mIndex_N_ITEM0() {
            return Memory.RAM.ReadS32(this.pointer + 0x2C);
        }
        
        private void _mIndex_N_ITEM0(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x2C, value);
        }
        
        private s32 _mIndex_N_ITEM1() {
            return Memory.RAM.ReadS32(this.pointer + 0x30);
        }
        
        private void _mIndex_N_ITEM1(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x30, value);
        }
        
        private s32 _mIndex_N_ITEM2() {
            return Memory.RAM.ReadS32(this.pointer + 0x34);
        }
        
        private void _mIndex_N_ITEM2(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x34, value);
        }
        
        private s32 _mIndex_N_ITEM3() {
            return Memory.RAM.ReadS32(this.pointer + 0x38);
        }
        
        private void _mIndex_N_ITEM3(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x38, value);
        }
        
        private s32 _mIndex_N_ITEM4() {
            return Memory.RAM.ReadS32(this.pointer + 0x3C);
        }
        
        private void _mIndex_N_ITEM4(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x3C, value);
        }
        
        private s32 _mIndex_N_ITEM5() {
            return Memory.RAM.ReadS32(this.pointer + 0x40);
        }
        
        private void _mIndex_N_ITEM5(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x40, value);
        }
        
        private s32 _mIndex_N_ITEM6() {
            return Memory.RAM.ReadS32(this.pointer + 0x44);
        }
        
        private void _mIndex_N_ITEM6(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x44, value);
        }
        
        private s32 _mIndex_N_ITEM7() {
            return Memory.RAM.ReadS32(this.pointer + 0x48);
        }
        
        private void _mIndex_N_ITEM7(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x48, value);
        }
        
        private s32 _mIndex_N_ITEM8() {
            return Memory.RAM.ReadS32(this.pointer + 0x4C);
        }
        
        private void _mIndex_N_ITEM8(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x4C, value);
        }
        
        private s32 _mIndex_N_ITEM9() {
            return Memory.RAM.ReadS32(this.pointer + 0x50);
        }
        
        private void _mIndex_N_ITEM9(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x50, value);
        }
        
        private s32 _mIndex_N_ITEM10() {
            return Memory.RAM.ReadS32(this.pointer + 0x54);
        }
        
        private void _mIndex_N_ITEM10(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x54, value);
        }
        
        private s32 _mIndex_N_ITEM11() {
            return Memory.RAM.ReadS32(this.pointer + 0x58);
        }
        
        private void _mIndex_N_ITEM11(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x58, value);
        }
        
        private s32 _mIndex_N_ITEM12() {
            return Memory.RAM.ReadS32(this.pointer + 0x5C);
        }
        
        private void _mIndex_N_ITEM12(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x5C, value);
        }
        
        private s32 _mIndex_N_ITEM13() {
            return Memory.RAM.ReadS32(this.pointer + 0x60);
        }
        
        private void _mIndex_N_ITEM13(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x60, value);
        }
        
        private s32 _mIndex_N_ITEM14() {
            return Memory.RAM.ReadS32(this.pointer + 0x64);
        }
        
        private void _mIndex_N_ITEM14(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x64, value);
        }
        
        private s32 _mIndex_N_ITEM15() {
            return Memory.RAM.ReadS32(this.pointer + 0x68);
        }
        
        private void _mIndex_N_ITEM15(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x68, value);
        }
        
        private s32 _mIndex_percent() {
            return Memory.RAM.ReadS32(this.pointer + 0x6C);
        }
        
        private void _mIndex_percent(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x6C, value);
        }
        
        private s32 _mIndex_ITEM0() {
            return Memory.RAM.ReadS32(this.pointer + 0x70);
        }
        
        private void _mIndex_ITEM0(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x70, value);
        }
        
        private s32 _mIndex_ITEM1() {
            return Memory.RAM.ReadS32(this.pointer + 0x74);
        }
        
        private void _mIndex_ITEM1(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x74, value);
        }
        
        private s32 _mIndex_ITEM2() {
            return Memory.RAM.ReadS32(this.pointer + 0x78);
        }
        
        private void _mIndex_ITEM2(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x78, value);
        }
        
        private s32 _mIndex_ITEM3() {
            return Memory.RAM.ReadS32(this.pointer + 0x7C);
        }
        
        private void _mIndex_ITEM3(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x7C, value);
        }
        
        private s32 _mIndex_ITEM4() {
            return Memory.RAM.ReadS32(this.pointer + 0x80);
        }
        
        private void _mIndex_ITEM4(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x80, value);
        }
        
        private s32 _mIndex_ITEM5() {
            return Memory.RAM.ReadS32(this.pointer + 0x84);
        }
        
        private void _mIndex_ITEM5(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x84, value);
        }
        
        private s32 _mIndex_ITEM6() {
            return Memory.RAM.ReadS32(this.pointer + 0x88);
        }
        
        private void _mIndex_ITEM6(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x88, value);
        }
        
        private s32 _mIndex_ITEM7() {
            return Memory.RAM.ReadS32(this.pointer + 0x8C);
        }
        
        private void _mIndex_ITEM7(s32 value) {
            Memory.RAM.WriteS32(this.pointer + 0x8C, value);
        }
    }
}
