//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dComIfG_inf_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public dSv_info_c save {get => this._save(); set => this._save(value);}//;
        
        public dComIfG_play_c play {get => this._play(); set => this._play(value);}//;
        
        //public dDlst_list_c drawlist {get => this._drawlist(); set => this._drawlist(value);}//;
        
        public u8[] field_0x1BF50 {get => this._field_0x1BF50(); set => this._field_0x1BF50(value);}//;
        
        //public dRes_control_c mResControl {get => this._mResControl(); set => this._mResControl(value);}//;
        
        public u8 field_0x1d1c0 {get => this._field_0x1d1c0(); set => this._field_0x1d1c0(value);}//;
        
        public u8 mBrightness {get => this._mBrightness(); set => this._mBrightness(value);}//;
        
        public dComIfG_inf_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        private dSv_info_c _save() {
            return new dSv_info_c(this.pointer + 0x00000);
        }
        
        private void _save(dSv_info_c value) {
        }
        
        private dComIfG_play_c _play() {
            return new dComIfG_play_c(this.pointer + 0x012A0);
        }
        
        private void _play(dComIfG_play_c value) {
        }
        
        /*private dDlst_list_c _drawlist() {
            return new dDlst_list_c(this.pointer + 0x05D1C);
        }
        
        private void _drawlist(dDlst_list_c value) {
        }*/
        
        // #ARRCOUNT 112
        private u8[] _field_0x1BF50() {
            u8[] bytes = new u8[112]; for(u32 i = 0; i < 112; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x1BF50 + (i * 1));} return bytes;
        }
        
        private void _field_0x1BF50(u8[] value) {
            for(u32 i = 0; i < 112; i++){Memory.RAM.WriteU8(this.pointer + 0x1BF50 + (i * 1), value[i]);}
        }
        
        /*private dRes_control_c _mResControl() {
            return new dRes_control_c(this.pointer + 0x1BFC0);
        }
        
        private void _mResControl(dRes_control_c value) {
        }*/
        
        private u8 _field_0x1d1c0() {
            return Memory.RAM.ReadU8(this.pointer + 0x1D1C0);
        }
        
        private void _field_0x1d1c0(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1D1C0, value);
        }
        
        private u8 _mBrightness() {
            return Memory.RAM.ReadU8(this.pointer + 0x1D1C1);
        }
        
        private void _mBrightness(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x1D1C1, value);
        }
    }
}
