//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dComIfG_play_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        //public dBgS mBgS {get => this._mBgS(); set => this._mBgS(value);}//;
        
        //public dCcS mCcS {get => this._mCcS(); set => this._mCcS(value);}//;
        
        public dADM mADM {get => this._mADM(); set => this._mADM(value);}//;
        
        public dStage_startStage_c mCurStage {get => this._mCurStage(); set => this._mCurStage(value);}//;
        
        public dStage_nextStage_c mNextStage {get => this._mNextStage(); set => this._mNextStage(value);}//;
        
        public u8[] field_0x3EAE {get => this._field_0x3EAE(); set => this._field_0x3EAE(value);}//;
        
        public dStage_stageDt_c mStageData {get => this._mStageData(); set => this._mStageData(value);}//;
        
        public dStage_roomControl_c mRoomCtrl {get => this._mRoomCtrl(); set => this._mRoomCtrl(value);}//;
        
        //public dEvt_control_c mEvtCtrl {get => this._mEvtCtrl(); set => this._mEvtCtrl(value);}//;
        
        public dEvent_manager_c mEvtManager {get => this._mEvtManager(); set => this._mEvtManager(value);}//;
        
        public dAttention_c mAttention {get => this._mAttention(); set => this._mAttention(value);}//;
        
        public u8[] field_0x46F8 {get => this._field_0x46F8(); set => this._field_0x46F8(value);}//;
        
        //public dVibration_c mVibration {get => this._mVibration(); set => this._mVibration(value);}//;
        
        //public dDetect_c mDetect {get => this._mDetect(); set => this._mDetect(value);}//;
        
        /*public JKRArchive mpMsgArchive {get => this._mpMsgArchive(); set => this._mpMsgArchive(value);}//;
        
        public JKRArchive mpDmsgArchive {get => this._mpDmsgArchive(); set => this._mpDmsgArchive(value);}//;
        
        public JKRArchive mpTmsgArchive {get => this._mpTmsgArchive(); set => this._mpTmsgArchive(value);}//;
        
        public JKRArchive mpMenuArchive {get => this._mpMenuArchive(); set => this._mpMenuArchive(value);}//;
        
        public JKRArchive mpFont0Archive {get => this._mpFont0Archive(); set => this._mpFont0Archive(value);}//;
        
        public JKRArchive mpFont1Archive {get => this._mpFont1Archive(); set => this._mpFont1Archive(value);}//;
        
        public JKRArchive mpAnmArchive {get => this._mpAnmArchive(); set => this._mpAnmArchive(value);}//;
        
        public JKRArchive mpLkDArc {get => this._mpLkDArc(); set => this._mpLkDArc(value);}//;
        
        public JKRArchive mpFmapArchive {get => this._mpFmapArchive(); set => this._mpFmapArchive(value);}//;
        
        public JKRArchive mpItemResArchive {get => this._mpItemResArchive(); set => this._mpItemResArchive(value);}//;
        
        public JKRArchive mpClctResArchive {get => this._mpClctResArchive(); set => this._mpClctResArchive(value);}//;
        
        public JKRArchive mpFmapResArchive {get => this._mpFmapResArchive(); set => this._mpFmapResArchive(value);}//;
        
        public JKRArchive mpDmapResArchive {get => this._mpDmapResArchive(); set => this._mpDmapResArchive(value);}//;
        
        public JKRArchive mpOptResArchive {get => this._mpOptResArchive(); set => this._mpOptResArchive(value);}//;
        
        public JKRArchive mpClothResArchive {get => this._mpClothResArchive(); set => this._mpClothResArchive(value);}//;
        
        public JKRArchive mpSaveResArchive {get => this._mpSaveResArchive(); set => this._mpSaveResArchive(value);}//;
        
        public JKRArchive mpItemIconArchive {get => this._mpItemIconArchive(); set => this._mpItemIconArchive(value);}//;
        
        public JKRArchive mpNameResArchive {get => this._mpNameResArchive(); set => this._mpNameResArchive(value);}//;
        
        public JKRArchive mpErrorResArchive {get => this._mpErrorResArchive(); set => this._mpErrorResArchive(value);}//;
        
        public JKRArchive mpActionIconArchive {get => this._mpActionIconArchive(); set => this._mpActionIconArchive(value);}//;
        
        public JKRArchive mpScopeResArchive {get => this._mpScopeResArchive(); set => this._mpScopeResArchive(value);}//;
        
        public JKRArchive mpCamResArchive {get => this._mpCamResArchive(); set => this._mpCamResArchive(value);}//;
        
        public JKRArchive mpSwimResArchive {get => this._mpSwimResArchive(); set => this._mpSwimResArchive(value);}//;
        
        public JKRArchive mpWindResArchive {get => this._mpWindResArchive(); set => this._mpWindResArchive(value);}//;
        
        public JKRArchive mpEnglishTextArchive {get => this._mpEnglishTextArchive(); set => this._mpEnglishTextArchive(value);}//;
        
        public JKRArchive mpHyruleTextArchive {get => this._mpHyruleTextArchive(); set => this._mpHyruleTextArchive(value);}//;
        
        public JKRAramBlock[] mAramHeap0 {get => this._mAramHeap0(); set => this._mAramHeap0(value);}//;
        
        public JKRAramBlock[] mAramHeap1 {get => this._mAramHeap1(); set => this._mAramHeap1(value);}//;
        
        public JKRAramBlock field_0x481c {get => this._field_0x481c(); set => this._field_0x481c(value);}//;
        
        public JKRAramBlock field_0x4820 {get => this._field_0x4820(); set => this._field_0x4820(value);}//;
        
        public JKRAramBlock[] mAramHeap0 {get => this._mAramHeap0(); set => this._mAramHeap0(value);}//;
        
        public JKRAramBlock[] mAramHeap1 {get => this._mAramHeap1(); set => this._mAramHeap1(value);}//;
        */
        
        public dComIfG_play_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        /*private dBgS _mBgS() {
            return new dBgS(this.pointer + 0x0000);
        }
        
        private void _mBgS(dBgS value) {
        }
        
        private dCcS _mCcS() {
            return new dCcS(this.pointer + 0x1404);
        }
        
        private void _mCcS(dCcS value) {
        }*/
        
        private dADM _mADM() {
            return new dADM(this.pointer + 0x3DF8);
        }
        
        private void _mADM(dADM value) {
        }
        
        private dStage_startStage_c _mCurStage() {
            return new dStage_startStage_c(this.pointer + 0x3E94);
        }
        
        private void _mCurStage(dStage_startStage_c value) {
        }
        
        private dStage_nextStage_c _mNextStage() {
            return new dStage_nextStage_c(this.pointer + 0x3EA0);
        }
        
        private void _mNextStage(dStage_nextStage_c value) {
        }
        
        // #ARRCOUNT 2
        private u8[] _field_0x3EAE() {
            u8[] bytes = new u8[2]; for(u32 i = 0; i < 2; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x3EAE + (i * 1));} return bytes;
        }
        
        private void _field_0x3EAE(u8[] value) {
            for(u32 i = 0; i < 2; i++){Memory.RAM.WriteU8(this.pointer + 0x3EAE + (i * 1), value[i]);}
        }
        
        private dStage_stageDt_c _mStageData() {
            return new dStage_stageDt_c(this.pointer + 0x3EB0);
        }
        
        private void _mStageData(dStage_stageDt_c value) {
        }
        
        private dStage_roomControl_c _mRoomCtrl() {
            return new dStage_roomControl_c(this.pointer + 0x3F34);
        }
        
        private void _mRoomCtrl(dStage_roomControl_c value) {
        }
        
        /*private dEvt_control_c _mEvtCtrl() {
            return new dEvt_control_c(this.pointer + 0x3F38);
        }
        
        private void _mEvtCtrl(dEvt_control_c value) {
        }*/
        
        private dEvent_manager_c _mEvtManager() {
            return new dEvent_manager_c(this.pointer + 0x402C);
        }
        
        private void _mEvtManager(dEvent_manager_c value) {
        }
        
        private dAttention_c _mAttention() {
            return new dAttention_c(this.pointer + 0x4568);
        }
        
        private void _mAttention(dAttention_c value) {
        }
        
        // #ARRCOUNT 8
        private u8[] _field_0x46F8() {
            u8[] bytes = new u8[8]; for(u32 i = 0; i < 8; i++){bytes[i] = Memory.RAM.ReadU8(this.pointer + 0x46F8 + (i * 1));} return bytes;
        }
        
        private void _field_0x46F8(u8[] value) {
            for(u32 i = 0; i < 8; i++){Memory.RAM.WriteU8(this.pointer + 0x46F8 + (i * 1), value[i]);}
        }
        
       /* private dVibration_c _mVibration() {
            return new dVibration_c(this.pointer + 0x4700);
        }
        
        private void _mVibration(dVibration_c value) {
        }
        
        private dDetect_c _mDetect() {
            return new dDetect_c(this.pointer + 0x4784);
        }
        
        private void _mDetect(dDetect_c value) {
        }
        
        private JKRArchive _mpMsgArchive() {
            return new JKRArchive(this.pointer + 0x4798);
        }
        
        private void _mpMsgArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpDmsgArchive() {
            return new JKRArchive(this.pointer + 0x479C);
        }
        
        private void _mpDmsgArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpTmsgArchive() {
            return new JKRArchive(this.pointer + 0x47A0);
        }
        
        private void _mpTmsgArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpMenuArchive() {
            return new JKRArchive(this.pointer + 0x47A4);
        }
        
        private void _mpMenuArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpFont0Archive() {
            return new JKRArchive(this.pointer + 0x47A8);
        }
        
        private void _mpFont0Archive(JKRArchive value) {
        }
        
        private JKRArchive _mpFont1Archive() {
            return new JKRArchive(this.pointer + 0x47AC);
        }
        
        private void _mpFont1Archive(JKRArchive value) {
        }
        
        private JKRArchive _mpAnmArchive() {
            return new JKRArchive(this.pointer + 0x47B0);
        }
        
        private void _mpAnmArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpLkDArc() {
            return new JKRArchive(this.pointer + 0x47B4);
        }
        
        private void _mpLkDArc(JKRArchive value) {
        }
        
        private JKRArchive _mpFmapArchive() {
            return new JKRArchive(this.pointer + 0x47B8);
        }
        
        private void _mpFmapArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpItemResArchive() {
            return new JKRArchive(this.pointer + 0x47BC);
        }
        
        private void _mpItemResArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpClctResArchive() {
            return new JKRArchive(this.pointer + 0x47C0);
        }
        
        private void _mpClctResArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpFmapResArchive() {
            return new JKRArchive(this.pointer + 0x47C4);
        }
        
        private void _mpFmapResArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpDmapResArchive() {
            return new JKRArchive(this.pointer + 0x47C8);
        }
        
        private void _mpDmapResArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpOptResArchive() {
            return new JKRArchive(this.pointer + 0x47CC);
        }
        
        private void _mpOptResArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpClothResArchive() {
            return new JKRArchive(this.pointer + 0x47D0);
        }
        
        private void _mpClothResArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpSaveResArchive() {
            return new JKRArchive(this.pointer + 0x47D4);
        }
        
        private void _mpSaveResArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpItemIconArchive() {
            return new JKRArchive(this.pointer + 0x47D8);
        }
        
        private void _mpItemIconArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpNameResArchive() {
            return new JKRArchive(this.pointer + 0x47DC);
        }
        
        private void _mpNameResArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpErrorResArchive() {
            return new JKRArchive(this.pointer + 0x47E0);
        }
        
        private void _mpErrorResArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpActionIconArchive() {
            return new JKRArchive(this.pointer + 0x47E4);
        }
        
        private void _mpActionIconArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpScopeResArchive() {
            return new JKRArchive(this.pointer + 0x47E8);
        }
        
        private void _mpScopeResArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpCamResArchive() {
            return new JKRArchive(this.pointer + 0x47EC);
        }
        
        private void _mpCamResArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpSwimResArchive() {
            return new JKRArchive(this.pointer + 0x47F0);
        }
        
        private void _mpSwimResArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpWindResArchive() {
            return new JKRArchive(this.pointer + 0x47F4);
        }
        
        private void _mpWindResArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpEnglishTextArchive() {
            return new JKRArchive(this.pointer + 0x47F8);
        }
        
        private void _mpEnglishTextArchive(JKRArchive value) {
        }
        
        private JKRArchive _mpHyruleTextArchive() {
            return new JKRArchive(this.pointer + 0x47FC);
        }
        
        private void _mpHyruleTextArchive(JKRArchive value) {
        }
        
        // #ARRCOUNT 3
        private JKRAramBlock[] _mAramHeap0() {
          JKRAramBlock[] substructs = new JKRAramBlock[3]; for(u32 i = 0; i < 3; i++){substructs[i] = new JKRAramBlock(this.pointer + 0x4800 + (i * JKRAramBlock.getSize()));}; return substructs;
        }
        
        private void _mAramHeap0(JKRAramBlock[] value) {
        }
        
        // #ARRCOUNT 4
        private JKRAramBlock[] _mAramHeap1() {
          JKRAramBlock[] substructs = new JKRAramBlock[4]; for(u32 i = 0; i < 4; i++){substructs[i] = new JKRAramBlock(this.pointer + 0x480C + (i * JKRAramBlock.getSize()));}; return substructs;
        }
        
        private void _mAramHeap1(JKRAramBlock[] value) {
        }
        
        private JKRAramBlock _field_0x481c() {
            return new JKRAramBlock(this.pointer + 0x481C);
        }
        
        private void _field_0x481c(JKRAramBlock value) {
        }
        
        private JKRAramBlock _field_0x4820() {
            return new JKRAramBlock(this.pointer + 0x4820);
        }
        
        private void _field_0x4820(JKRAramBlock value) {
        }
        
        // #ARRCOUNT 3
        private JKRAramBlock[] _mAramHeap0() {
          JKRAramBlock[] substructs = new JKRAramBlock[3]; for(u32 i = 0; i < 3; i++){substructs[i] = new JKRAramBlock(this.pointer + 0x47FC + (i * JKRAramBlock.getSize()));}; return substructs;
        }
        
        private void _mAramHeap0(JKRAramBlock[] value) {
        }
        
        // #ARRCOUNT 4
        private JKRAramBlock[] _mAramHeap1() {
          JKRAramBlock[] substructs = new JKRAramBlock[4]; for(u32 i = 0; i < 4; i++){substructs[i] = new JKRAramBlock(this.pointer + 0x480C + (i * JKRAramBlock.getSize()));}; return substructs;
        }
        
        private void _mAramHeap1(JKRAramBlock[] value) {
        }
       */
    }
}
