//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dAttDraw_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        //public mDoExt_McaMorf anm {get => this._anm(); set => this._anm(value);}//;
        
        //public J3DAnmColor mpAnmClr {get => this._mpAnmClr(); set => this._mpAnmClr(value);}//;
        
        //public J3DMatColorAnm mpAnmMatClr {get => this._mpAnmMatClr(); set => this._mpAnmMatClr(value);}//;
        
        public dAttDraw_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x0; // DEADBEEF TODO: Fix Addr
        }
        
        /*private mDoExt_McaMorf _anm() {
            return new mDoExt_McaMorf(this.pointer + 0x0);
        }
        
        private void _anm(mDoExt_McaMorf value) {
        }
        
        private J3DAnmColor _mpAnmClr() {
            return new J3DAnmColor(this.pointer + 0x4);
        }
        
        private void _mpAnmClr(J3DAnmColor value) {
        }
        
        private J3DMatColorAnm _mpAnmMatClr() {
            return new J3DMatColorAnm(this.pointer + 0x8);
        }
        
        private void _mpAnmMatClr(J3DMatColorAnm value) {
        }*/
    }
}
