//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dAttCatch_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public u32 field_0x0 {get => this._field_0x0(); set => this._field_0x0(value);}//;
        
        public u32 field_0x4 {get => this._field_0x4(); set => this._field_0x4(value);}//;
        
        public f32 field_0x8 {get => this._field_0x8(); set => this._field_0x8(value);}//;
        
        public u8 field_0xc {get => this._field_0xc(); set => this._field_0xc(value);}//;
        
        public u8 field_0xd {get => this._field_0xd(); set => this._field_0xd(value);}//;
        
        public u8 field_0xe {get => this._field_0xe(); set => this._field_0xe(value);}//;
        
        public u8 field_0xf {get => this._field_0xf(); set => this._field_0xf(value);}//;
        
        public u32 mCatghTargetID {get => this._mCatghTargetID(); set => this._mCatghTargetID(value);}//;
        
        public u8 mChangeItem {get => this._mChangeItem(); set => this._mChangeItem(value);}//;
        
        public dAttCatch_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x18;
        }
        
        private u32 _field_0x0() {
            return Memory.RAM.ReadU32(this.pointer + 0x00);
        }
        
        private void _field_0x0(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x00, value);
        }
        
        private u32 _field_0x4() {
            return Memory.RAM.ReadU32(this.pointer + 0x04);
        }
        
        private void _field_0x4(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x04, value);
        }
        
        private f32 _field_0x8() {
            return Memory.RAM.ReadF32(this.pointer + 0x08);
        }
        
        private void _field_0x8(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x08, value);
        }
        
        private u8 _field_0xc() {
            return Memory.RAM.ReadU8(this.pointer + 0x0C);
        }
        
        private void _field_0xc(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x0C, value);
        }
        
        private u8 _field_0xd() {
            return Memory.RAM.ReadU8(this.pointer + 0x0D);
        }
        
        private void _field_0xd(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x0D, value);
        }
        
        private u8 _field_0xe() {
            return Memory.RAM.ReadU8(this.pointer + 0x0E);
        }
        
        private void _field_0xe(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x0E, value);
        }
        
        private u8 _field_0xf() {
            return Memory.RAM.ReadU8(this.pointer + 0x0F);
        }
        
        private void _field_0xf(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x0F, value);
        }
        
        private u32 _mCatghTargetID() {
            return Memory.RAM.ReadU32(this.pointer + 0x10);
        }
        
        private void _mCatghTargetID(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x10, value);
        }
        
        private u8 _mChangeItem() {
            return Memory.RAM.ReadU8(this.pointer + 0x14);
        }
        
        private void _mChangeItem(u8 value) {
            Memory.RAM.WriteU8(this.pointer + 0x14, value);
        }
    }
}
