//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TWW.API {
    
    
    public class dAttList_c {
        
        [System.Text.Json.Serialization.JsonIgnoreAttribute()]
        private u32 pointer;
        
        public f32 mWeight {get => this._mWeight(); set => this._mWeight(value);}//;
        
        public f32 mDistance {get => this._mDistance(); set => this._mDistance(value);}//;
        
        public u32 mType {get => this._mType(); set => this._mType(value);}//;
        
        public u32 mActorID {get => this._mActorID(); set => this._mActorID(value);}//;
        
        public dAttList_c(u32 pointer) {
           this.pointer = pointer;
        }
        
        public static uint getSize() {
          return 0x10;
        }
        
        private f32 _mWeight() {
            return Memory.RAM.ReadF32(this.pointer + 0x0);
        }
        
        private void _mWeight(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x0, value);
        }
        
        private f32 _mDistance() {
            return Memory.RAM.ReadF32(this.pointer + 0x4);
        }
        
        private void _mDistance(f32 value) {
            Memory.RAM.WriteF32(this.pointer + 0x4, value);
        }
        
        private u32 _mType() {
            return Memory.RAM.ReadU32(this.pointer + 0x8);
        }
        
        private void _mType(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0x8, value);
        }
        
        private u32 _mActorID() {
            return Memory.RAM.ReadU32(this.pointer + 0xC);
        }
        
        private void _mActorID(u32 value) {
            Memory.RAM.WriteU32(this.pointer + 0xC, value);
        }
    }
}
